### ISSUE TITLE
Publish Kani and Kani macro documentation to github.io

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#1008]
Until we can publish the crates `kani` and `kani-macro` in crates.io, I think we should upload the documentation of those crates to github.io. One way we can accomplish that is to build the documentation via `cargo doc` and copy them to docs/book as part of the `build-docs.sh` script.

I haven't really dived deep into this issue, so there might be better ways to do that.

Maybe we can publish all the docs including the ones for our binaries, but we probably want to somehow differentiate them so it's clear for our users which APIs they should use and which ones are for Kani developers.

**Comment by celinval** [comment]
BTW, we should fix these warnings as part of this work:
```
warning: this URL is not a hyperlink
 --> library/kani/src/invariant.rs:8:5
  |
8 | /// https://doc.rust-lang.org/stable/nomicon/what-unsafe-does.html for examples of valid values.
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://doc.rust-lang.org/stable/nomicon/what-unsafe-does.html>`
  |
  = note: `#[warn(rustdoc::bare_urls)]` on by default
  = note: bare URLs are not automatically turned into clickable links

warning: this URL is not a hyperlink
  --> library/kani/src/invariant.rs:64:10
   |
64 | /// Ref: https://doc.rust-lang.org/stable/nomicon/what-unsafe-does.html
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://doc.rust-lang.org/stable/nomicon/what-unsafe-does.html>`
   |
   = note: bare URLs are not automatically turned into clickable links

warning: `kani` (lib doc) generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 1.01s

```

**Comment by tedinski** [comment]
One possibility here is we could just publish these to crates.io but put in our readme that we don't recommend consuming them from crates.io as they're included as part of a Kani install. This would get us the standard documentation location in docs.rs though
