### ISSUE TITLE
Preserve debug logging in release mode

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#1019]
I think we should ensure that our released version of Kani can still emit debug logs. It seems when we build with `cargo build --release` we get a version where running with `--debug` no longer triggers `tracing::debug!` lines.

Or at least, it seems like that's what's going on. I haven't investigated further yet.

I think this is a "must have" because we might want our customers to save a debug log and send it to us.

**Comment by celinval** [comment]
See https://docs.rs/tracing/latest/tracing/level_filters/index.html#compile-time-filters
