### ISSUE TITLE
Hide Sanity Checks from Output

### ISSUE THREAD

**Issue by jaisnan** [model-checking/kani#1020]
Requested feature:

There are a lot of Sanity checks present in the final output that need to be hidden from the final presentation to the user. They add a lot of noise and this change would help the user find relevant information quicker.

Tagging this as a "must have" because with the Property Class changes, this should be relatively easy to add, maybe first behind an experimental flag.

**Comment by zhassan-aws** [comment]
Related to #842

**Comment by jaisnan** [comment]
Note: only filter success cases. If a sanity_check fails, the verification needs to fail as well.
