### ISSUE TITLE
Kani seems to hang indefinitely with arrays

### ISSUE THREAD

**Issue by cameron1024** [model-checking/kani#1165]
I'm just getting started with Kani, so apologies is this is a beginner mistake:

I tried this code:

```rust
fn rev(mut x: [i32; 4]) -> [i32; 4] {
    x.reverse();
    x
}


#[cfg(kani)]
#[kani::proof]
fn example() {
    let var = kani::any();
    let reversed = rev(var);
    let double_reversed = rev(reversed);

    assert_eq!(var, double_reversed);
}
```

using the following command line invocation:

```
kargo-kani
```

with Kani version: 0.1.0

I expected this to either verify or fail to verify, but instead the command hangs on "Checking harness example...". I'm not sure if there's something here that drastically hurts performance? I've tried a few other examples that don't use arrays, and they seem to work pretty much instantly.

Is this a bug? Or am I doing something wrong? 

Thanks :grin:

**Comment by zhassan-aws** [comment]
Thanks for posting this issue! For most examples involving loops, the `--default-unwind` option needs to be specified. For the example you posted, running with `--default-unwind 17` completes successfully (typically one wants to start with a smaller unwind value and increase it if an unwinding assertion fails).

Not producing any output is an issue that we plan on addressing: https://github.com/model-checking/kani/issues/493

**Comment by tedinski** [comment]
Alternatively, `#[kani::unwind(17)]` on the proof harness.

**Comment by zhassan-aws** [comment]
This value represents the number of times loops will be unrolled. For example, on the following program:
```rust
#[kani::proof]
fn sum_array() {
    let a = [1, 2, 3, 4];
    let mut sum = 0;
    for i in a {
        sum += i;
    }
    assert!(sum == 10);
}
```
the loop needs to be unrolled 4 times for the assert to be proven. In general, if a loop needs to be unrolled n times, one needs to specify an unwinding of n+1 (either by adding a `#[kani::unwind(n+1)]` attribute to the harness, or by running with `--default-unwind n+1`. For the `sum_array` example above, specifying an unwinding less than 5 would result in verification failure with the message:
```
 ** 1 of 57 failed (56 undetermined)
Failed Checks: unwinding assertion loop 0
 File: "/home/ubuntu/examples/sum_array.rs", line 5, in sum_array

VERIFICATION:- FAILED

[Kani] info: Verification output shows one or more unwinding failures.
[Kani] tip: Consider increasing the unwinding value or disabling `--unwinding-assertions`.
```
On the other hand, verification would pass with any unwinding value greater than or equal to 5, although using a value much bigger than 5 may make the verification problem unnecessarily complicated.

Check out the CBMC documentation on unwinding for a more detailed explanation: https://github.com/diffblue/cbmc/blob/develop/doc/cprover-manual/cbmc-unwinding.md

**Comment by cameron1024** [comment]
Thanks for the clarification, that makes a lot of sense 😁
