### ISSUE TITLE
Standard RMC include

### ISSUE THREAD

**Issue by danielsn** [model-checking/kani#119]
Requested feature: Currently, we have to give stubs for `nondet`, `assume` etc. We should be able to import these using a standard `use` declaration
Use case: Make it easier to include these. Makes it easier to update them as needed.
Link to relevant documentation (Rust reference, Nomicon, RFC):
Is this a breaking change?

Test case:

```rust
<code>
```

**Comment by zhassan-aws** [comment]
All the requested features have been implemented. Closing this issue.
