### ISSUE TITLE
Add support to cargo workspace

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#1207]
Requested feature: Add a `--workspace` option to `cargo-kani`.
Use case: User want to check all harnesses from all crates in the workspace. This may already work today for Cargo.toml that only define workspace, but I believe it we will need the explicit option for cases where one Cargo.toml defines a package and a workspace.
Link to relevant documentation (Rust reference, Nomicon, RFC):

**Comment by tedinski** [comment]
Fixed! #1510
