### ISSUE TITLE
Overflow checks should abort the execution

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#1208]
I tried this code:

```rust
#[kani::proof]
fn check_sub_overflow() {
    let a = [0; 5];
    let ptr0: *const i32 = &a[0];
    let ptr1: *const i32 = &a[1];
    let _: usize = ptr0 as usize - ptr1 as usize;
    unreachable!("Previous statement should fail");
}
```

using the following command line invocation:

```
kani check.rs
```

with Kani version: *0.2*

I expected to see this happen: There should be an overflow check failure but the unreachable code should not panic since it is unreachable ([playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1cca359f4da63c0b73b228acd0a6396d)).

Instead, this happened: Both checks fail, the overflow check and the unreachable panic.

**Comment by adpaco-aws** [comment]
Yes, there are many places where we assert false but we should be using (assert + assume) false. If I'm not mistaken, this would be covered by the "assertions audit" described in #1056.
