### ISSUE TITLE
Memory blows up on a simple two-dimensional vector example

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#1226]
I tried this code:

```rust
#[cfg_attr(kani, kani::proof, kani::unwind(3))]
fn main() {
    let mut v1: Vec<Vec<i32>> = Vec::new();
    v1.push(vec![1, 2]);
    v1.push(vec![3]);

    let v2: Vec<i32> = v1.into_iter().flatten().collect();
    assert_eq!(v2, vec![1, 2, 3]);
}
```

using the following command line invocation:

```
kani 2d.rs
```

with Kani version:

I expected to see this happen: Verification successful

Instead, this happened: Memory usage went up to ~25 GB in about 90 seconds.

**Comment by zhassan-aws** [comment]
An immutable version of the above program doesn't run out of memory, but it doesn't terminate in 1 hour with an `unwind` value of 6:
```rust
#[cfg_attr(kani, kani::proof, kani::unwind(6))]
fn main() {
    let v1: Vec<Vec<i32>> = vec![vec![1, 2], vec![3]];

    let v2: Vec<i32> = v1.into_iter().flatten().collect();
    assert_eq!(v2, vec![1, 2, 3]);
}
```
If I reduce the `unwind` value to 5, it finishes in ~25 minutes and uses 7 GB of memory, but an unwinding assertion fails.

**Comment by tedinski** [comment]
The probable cause of this is that:

1. `Vec` internally uses unions. 
2. That union gets partially initialized because it's not using the "larger case"
3. That means `nondet` remains in that memory
4. So it can't be constant-propagated
5. And results allocations of nondet size

**Comment by zhassan-aws** [comment]
For the record, a smaller version of the above program:
```rust
#[cfg_attr(kani, kani::proof, kani::unwind(5))]
fn main() {
    let v1: Vec<Vec<i32>> = vec![vec![1], vec![]];

    let v2: Vec<i32> = v1.into_iter().flatten().collect();
    assert_eq!(v2, vec![1]);
}
```
completes in 34 minutes with a minimum unwind of 5 and uses 6.3GB of memory.

**Comment by tautschnig** [comment]
With diffblue/cbmc#7230 on top of diffblue/cbmc@70b7cf7baf735f I get "Verification Time: 74.53128s" when it takes 86.885506s using diffblue/cbmc@70b7cf7baf735f and Kani revision 057926b83c. These are numbers referring to https://github.com/model-checking/kani/issues/1226#issuecomment-1139740487. It seems further investigation is necessary here.

**Comment by tautschnig** [comment]
Changes to CBMC to be PR'ed, but I have now gotten this down to 2 seconds.

**Comment by zhassan-aws** [comment]
Awesome! Is the PR also related to unions?

**Comment by tautschnig** [comment]
My further changes are all extensions to expression simplification, but it's probably necessary to have union field-sensitivity in place as well for otherwise there might just not be anything to propagate (and then simplify).
