### ISSUE TITLE
Proper message for successful assertion

### ISSUE THREAD

**Issue by Djazouli** [model-checking/kani#1240]
Requested feature:
Replace `assertion failed` with another clearer message like `assertion holds` when an assertion is indeed provable.

Test case:
This example in the doc:

https://github.com/model-checking/kani/blob/6213b0b2200f9e468f2494c738bdc19cb31ef222/docs/src/verification-results.md?plain=1#L37

```rust
fn success_example() {
    let mut sum = 0;
    for i in 1..4 {
        sum += i;
    }
    assert_eq!(sum, 6);
}
```

outputs:

```bash
Check 4: success_example.assertion.4
         - Status: SUCCESS
         - Description: "assertion failed: sum == 6"
```

But the assertion did not fail, it actually holds.

Note: This may be linked to [https://github.com/model-checking/kani/issues/189](https://github.com/model-checking/kani/issues/189), but the issue was closed.

**Comment by tedinski** [comment]
Recently we discussed changing "Description" to something else in certain cases. What do you think of something like:

```
Check 4: success_example.assertion.4
         - Status: SUCCESS
         - Panic message: "assertion failed: sum == 6"
```

Would that have made things at all clearer?

**Comment by Djazouli** [comment]
I think seeing ` - Panic message: "assertion failed: sum == 6"` would have made me wonder why it panicked. But I agree that a well-found prefix may help to clarify the description. Even if in an ideal world, we would like to have control over the panic messages generated be the standard library.

Maybe writing a few words about it in the documentation may help too ? Maybe just after the example that we mentionned before ?
But a keen reader may have been surprised even before, when fixing the example as mentionned here: https://github.com/model-checking/kani/blob/6213b0b2200f9e468f2494c738bdc19cb31ef222/docs/src/install-guide.md?plain=1#L137

This reader will notice that even after fixing the example, the description still states `assertion failed`.

**Comment by jaisnan** [comment]
Thank you for the suggestions @Djazouli! Would it be less confusing if we didn't show information about the Checks that passed by default ? (ex - assertions that hold well)? We had plans of re-doing the output - https://github.com/model-checking/kani/issues/1194 and would love to know your thoughts on the proposed plan and if it would be an improvement over what you experience currently.

**Comment by Djazouli** [comment]
Thank you for your answers !
Yes, I think having no information (by default of course) about the checks that passed would have made it less confusing. It is kind of implicit that if the status is **SUCCESS**, all the assertions holds. But it may just feel like _hiding_ the issue, that will reappear if someone enables a higher level of verbosity.

I'll see if I have any interesting input on the issue you just linked, thank you !

**Comment by adpaco-aws** [comment]
As mentioned in #2177 and also here, we'd like to focus on a long-term solution for our output. Please let's continue the discussion in #1194.
