### ISSUE TITLE
Failing regression in MacOs CI

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#134]
MacOs GitHub Actions have suddenly started to fail on the test:
```
 rust-tests/cbmc-reg/FatPointers/slice2.rs
```

See the following run: https://github.com/model-checking/rmc/actions/runs/860971843

The failure does not reproduce locally.  #133 will disable this test for the time being.

**Comment by zhassan-aws** [comment]
Tracked on CBMC side by https://github.com/diffblue/cbmc/issues/6731.
