### ISSUE TITLE
Audit function signature codegen

### ISSUE THREAD

**Issue by fzaiser** [model-checking/kani#1365]
The code of `closure_sig` is copy-pasted from `fn_sig_for_fn_abi` in `compiler/rustc_middle/src/ty/layout.rs`. We may have to do something similar for generators (#416), so it would be good if we could use the rustc function `fn_abi_of_instance` directly (as the comment on `fn_sig_for_fn_abi` suggests. This would prevent problems with keeping in sync with rustc.

**Comment by fzaiser** [comment]
The relevant function `fn_sig_for_fn_abi` is [here](https://github.com/rust-lang/rust/blob/848090dcd18553b790461132ca9d2a020aeea9a2/compiler/rustc_middle/src/ty/layout.rs#L2754). It has a comment saying:
```rust
    // NOTE(eddyb) this is private to avoid using it from outside of
    // `fn_abi_of_instance` - any other uses are either too high-level
    // for `Instance` (e.g. typeck would use `Ty::fn_sig` instead),
    // or should go through `FnAbi` instead, to avoid losing any
    // adjustments `fn_abi_of_instance` might be performing.
```

So the question is whether we should use `Ty::fn_sig` or `fn_abi_of_instance`. To find out, I looked at the cranelift backend. They use [this function](https://github.com/rust-lang/rust/blob/b629c85bd74dfb730a3e9308312b007c0bf027cb/compiler/rustc_codegen_cranelift/src/abi/mod.rs#L52) to obtain the signature of a function/closure/generator. I presume we should do something similar.

Note that the `fn_abi_of_instance` function makes some adjustments to the signature returned by the private function `fn_sig_for_fn_abi`: they happen in the call to `fn_abi_new_uncached` [here](https://github.com/rust-lang/rust/blob/848090dcd18553b790461132ca9d2a020aeea9a2/compiler/rustc_middle/src/ty/layout.rs#L3163), in that function they call `fn_abi_adjust_for_abi` [here](https://github.com/rust-lang/rust/blob/848090dcd18553b790461132ca9d2a020aeea9a2/compiler/rustc_middle/src/ty/layout.rs#L3364), which is defined just below.

**Comment by fzaiser** [comment]
@celinval The adjustments to the signature could be related to #1350. These adjustments don't currently happen in the Kani code, but they probably should.

**Comment by celinval** [comment]
Totally! We should investigate if using `fn_abi_of_instance` would simplify how we handle functions today. I believe this is also related to the issue we were having with closure to function pointer casting: #274

**Comment by celinval** [comment]
Note that the function ABI will include the tracker location when required, so #374 and this issue are somewhat related.
