### ISSUE TITLE
Buid Kani on arm linux

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#1367]
We've got Kani building on M1, now let's get it building on arm linux.

Out of scope is CI/install, just like M1.

**Comment by diagprov** [comment]
Hello, I was a bit behind thanks to life things. I checked the model on some arm64 boards and M1s in the M1 thread and missed this new one: https://github.com/model-checking/kani/issues/1167#issuecomment-1190515961

Summary is, it looks like the model will need to differentiate between Linux and Apple/Darwin.

I've built cbmc, cbmc-viewer and run kani/kani-regression with ppc64le (only fails due to inline asm being experimental on non-mainline rust targets) so I think I can probably do this for a T1 Rust target (aarch64) as well if nobody is working on it.

**Comment by tedinski** [comment]
Sure! I was hoping to work on it soon, but I've had other priorities. I'd be happy to accept a PR that adds the Arm Linux machine model and gets Kani working on that platform. :)

**Comment by diagprov** [comment]
Ok, I'll have a go. Would definitely be good to get some reviews though, I'm learning about CBMC on the fly.

**Comment by tedinski** [comment]
Just adding a link to github actions issues about arm linux support:

* https://github.com/actions/runner-images/issues/5631

**Comment by adpaco-aws** [comment]
In addition, I haven't been able to build CBMC from source neither:

```
Checking /home/ubuntu/cbmc/src/ansi-c/library/stdio.c
__libcheck.c: In function ‘__isoc99_vfscanf’:
__libcheck.c:1050:31: error: incompatible type for argument 1 of ‘__CPROVER_OBJECT_SIZE’
 1050 |         __CPROVER_OBJECT_SIZE(arg))
      |                               ^~~
      |                               |
      |                               va_list
In file included from ./library/cprover.h:72,
                 from <command-line>:
./library/../cprover_builtin_headers.h:59:40: note: expected ‘const void *’ but argument is of type ‘va_list’
   59 | __CPROVER_size_t __CPROVER_OBJECT_SIZE(const void *);
      |                                        ^~~~~~~~~~~~
__libcheck.c: In function ‘__isoc99_vsscanf’:
__libcheck.c:1213:31: error: incompatible type for argument 1 of ‘__CPROVER_OBJECT_SIZE’
 1213 |         __CPROVER_OBJECT_SIZE(arg))
      |                               ^~~
      |                               |
      |                               va_list
In file included from ./library/cprover.h:72,
                 from <command-line>:
./library/../cprover_builtin_headers.h:59:40: note: expected ‘const void *’ but argument is of type ‘va_list’
   59 | __CPROVER_size_t __CPROVER_OBJECT_SIZE(const void *);
      |                                        ^~~~~~~~~~~~
__libcheck.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-gnu-line-marker’ may have been intended to silence earlier diagnostics
rm: cannot remove '__libcheck.s': No such file or directory
make[2]: *** [src/ansi-c/CMakeFiles/ansi-c.dir/build.make:279: src/ansi-c/library-check.stamp] Error 1
make[2]: Leaving directory '/home/ubuntu/cbmc/build'
make[1]: *** [CMakeFiles/Makefile2:2075: src/ansi-c/CMakeFiles/ansi-c.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/cbmc/build'
make: *** [Makefile:166: all] Error 2
make: Leaving directory '/home/ubuntu/cbmc/build'
```

**Comment by adpaco-aws** [comment]
I've been able to fix the two tests above, but now there's some more failures on the `ui` regression suite:

```
failures:
    [expected] ui/concrete-playback/array/main.rs
    [expected] ui/concrete-playback/custom/main.rs
    [expected] ui/concrete-playback/i8/main.rs
    [expected] ui/concrete-playback/non_zero/main.rs
    [expected] ui/concrete-playback/option/main.rs
    [expected] ui/concrete-playback/result/main.rs
    [expected] ui/concrete-playback/u8/main.rs

test result: FAILED. 97 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out; finished in 18.54s
```

**Comment by adpaco-aws** [comment]
> I've been able to fix the two tests above, but now there's some more failures on the ui regression suite

All these seem to be failing for the same reason, let me explain using `ui/concrete-playback/u8/main.rs` as an example.
The test expects concrete playback to print the following:

```rs
#[test]
fn kani_concrete_playback_harness
    let concrete_vals: Vec<Vec<u8>> = vec![
        // 0
        vec![0],
        // 101
        vec![101],
        // 255
        vec![255]
    ];
    kani::concrete_playback_run(concrete_vals, harness);
}
```

However, in ARM64 Linux it's print this:

```rs
#[test]
fn kani_concrete_playback_harness_6199617291819462955() {
    let concrete_vals: Vec<Vec<u8>> = vec![
        // 0
        vec![0],
        // 'e'
        vec![101],
        // 255
        vec![255],
    ];
    kani::concrete_playback_run(concrete_vals, harness);
}
```
Note that the interpreted value for the byte with value 101 is `'e'`.

At first, I thought this could be a formatting issue in Kani, but apparently the value is already `'e'` when we extract it from the trace. The trace item is being deserialized into a `String`; maybe the ASCII values are coming from CBMC?

**Comment by tautschnig** [comment]
Yes, that’s CBMC’s doing: one peculiarity of ARM64 is that the char type is unsigned. That makes CBMC print ASCII characters here.

**Comment by AGSaidi** [comment]
It’s amazing how many times that choice has bitten Arm software.  Either making the ‘char’ explicitly ‘signed char’ or building with ‘-fsigned-char’ should fix it.

**Comment by adpaco-aws** [comment]
Thank you @tautschnig and @AGSaidi !

Got some good news: All other tests in our standard regression suites are passing 😄
