### ISSUE TITLE
Missing bundle for aarch64-apple-darwin on v0.6.0

### ISSUE THREAD

**Issue by Oppen** [model-checking/kani#1370]
Running the following after the new v0.6.0 release (supposed to include support for Apple silicon):
```shell
$ cargo install --locked kani-verifier                                                       
    Updating crates.io index                                        
  Downloaded kani-verifier v0.6.0                                                                                                       
  Downloaded 1 crate (13.6 KB) in 2.21s                                                                                                 
  Installing kani-verifier v0.6.0                                   
   Compiling log v0.4.17                                            
   Compiling cfg-if v1.0.0                                          
   Compiling anyhow v1.0.58                                                                                                             
   Compiling kani-verifier v0.6.0                                                                                                       
   Compiling home v0.5.3                                            
   Compiling os_info v3.4.0                                         
    Finished release [optimized] target(s) in 5.92s                 
   Replacing /Users/pelito/.cargo/bin/cargo-kani                                                                                        
   Replacing /Users/pelito/.cargo/bin/kani                                                                                              
    Replaced package `kani-verifier v0.5.0` with `kani-verifier v0.6.0` (executables `cargo-kani`, `kani`)

$ cargo-kani setup       
[0/6] Running Kani first-time setup...                              
[1/6] Ensuring the existence of: /Users/pelito/.kani/kani-0.6.0                                                                         
[2/6] Downloading Kani release bundle: kani-0.6.0-aarch64-apple-darwin.tar.gz                                                           
Error: Kani does not support this platform (Rust target aarch64-apple-darwin) 
```

**Comment by tedinski** [comment]
There is no CI for Apple Silicon. (And may not be for awhile. Github Actions may not plan to support it ever, and I'm not sure if we'll want to set up and maintain our own infrastructure for that.)

We need to clarify that in the documentation and error message.

The only level of support we have so far is that you can now build from source, not yet install via `cargo install`.

**Comment by Oppen** [comment]
Sad to hear. Then, I have a different question. Say I also have some x86 hosts to run the proofs (and I'm happy with extrapolating the proof), would having kani code break my build on M1 if I use it for x86?

**Comment by tedinski** [comment]
If I understand your question correctly: no it shouldn't break anything.

Kani proofs already need to be written under `cfg(kani)` somehow. This is only set when running `cargo kani`. For example:

```
#[cfg(kani)]
mod proofs {
  // ... like a tests block
}
```

or individually

```
#[cfg(kani)]
#[kani::proof]
fn check_etc() ...
```

Will ensure these don't get built normally.

(This is partially because we haven't yet fixed a few ergonomic issues, and don't yet publish the `kani` crate on `crates.io`. Once we do that, some of these extra annotations can maybe be relaxed (in that future) by adding `kani` as a `dev-dependency`. But this shouldn't break any builds because when it's not `cfg(kani)` it shouldn't do much of anything at all.)

**Comment by Oppen** [comment]
Yep, that's what I was asking, and your answer is satisfying. Thank you!
