### ISSUE TITLE
Kani generates array accesses on zero-sized arrays

### ISSUE THREAD

**Issue by giltho** [model-checking/kani#1413]
# Overview

It looks like the following code, which is extracted from tests/kani/os_str_reduced.rs is causing kani to produce an array indexing expression that is applied to an Array of size 0.
```rust
use std::mem;

struct Inner {
    pub inner: [u8],
}

impl Inner {
    fn from_u8_slice(s: &[u8]) -> &Inner {
        unsafe { mem::transmute(s) }
    }
}

#[kani::proof]
fn main() {
    let inner = Inner::from_u8_slice(b"hi");
    let _y = inner.inner[0];
}
```
This causes the Kanillian backend to crash at compilation. I'm not sure if this is expected behaviour or a bug.
There are 134 array expressions being generated by kani on the `tests/kani` test suite, and only one of the is in that case.

----

# Investigation

The corresponding mir of the operation that fails is the following
```rust
 _5 = ((*_1).0: [u8])[_6];        // scope 1 at /home/ubuntu/kani/tests/kani/Strings/os_str_reduced.rs:20:14: 20:28         
```

After investigating, it seems that it is due to the fact that the slice type is compiled to a zero-sized array type.
```
struct Inner
{
  // inner
  unsigned char inner[0];
};
```

If this is expected behaviour, I'll just tweak my compiler to accept this special case

**Comment by tedinski** [comment]
I haven't investigated anything yet, just thinking out loud:

1. I believe `struct Inner` there is supposed to be a flexible array struct. I'm not sure if we're actually generating the equivalent of `char inner[0];` there or if that's the gen-c printer using the old school pre-standardization syntax (would now be `char inner[];`). This is a legit legal C construct though.
2. One of the things Kani frequently does is use `&expr[0]` to get the pointer of `expr`. I can't remember the reasons why. I found it annoying early on but gave up trying to fix it. I might just not have been experienced enough at digging into kani-compiler and cbmc goto-c at that time. However, that doesn't seem to be what's happening here since there's no address-of?

**Comment by giltho** [comment]
So it's definitely generating the type `char inner[0]`, because the Irep I parse is `Array(u8, 0)`. That might be CBMC's version of flexible array struct.
The reason it crashes Kanillian is that I'm expecting the rvalue `inner` to represent an array in memory, but my compiler actually detects it as a ZST, and crashes saying "wait that isn't in memory". For the case of arrays, I can actually hijack that reasoning for the specific case of 0-sized arrays.

**Comment by tedinski** [comment]
Oh right, the original code has `inner.inner[0]` so it's legit trying to access it.

Try running a struct with a flexible array through cbmc's c compiler and see what irep it generates.

It might be that it produces "array of size 0" for that, in which case that should be special cased.

But if it produces something else, then maybe Kani should be updated...

**Comment by tautschnig** [comment]
Flexible arrays without an initializer will have array size zero, but then also any access is out of bounds. In this case (my Rust foo isn't good enough): would you expect an initializer to be present, perhaps one that sets the size to three? There are only two supported scenarios with flexible array members:

1) The object has static lifetime, and an initializer is present. In this case, the front-end (i.e., Kani) needs to set up the actual size. (The fact we are dealing with a flexible array member then is just an annotation for the purpose of getting `sizeof` right.)
2) The object is allocated on the heap. The front-end cannot fix this case for the actual size will depend on the (runtime-decided) actual allocation size. Bounds checking honors this and looks at the size of the allocation, and not the size of the data type.

**Comment by celinval** [comment]
This is the expected behavior. What happens here is a transmute on the fat pointer. So you'll end up with a &Inner fat pointer that has the length of the byte array and a pointer to the data. The data pointed to is `b"hi"`

**Comment by giltho** [comment]
Alright, I've added this as [an unhandled feature](https://github.com/giltho/Kanillian/blob/master/kanillian/lib/compiler/stats.ml#L24) for now, and will deal with it when needed.
There's only 10 occurrences on the entire test suite so it seems fine to deal with it later
