### ISSUE TITLE
Better Behavior for `cargo kani`: workspaces and `--manifest-path`

### ISSUE THREAD

**Issue by YoshikiTakashima** [model-checking/kani#1420]
Requested feature: `cargo kani` should have `cargo test` like semantics. Workspaces should be supported,

Use case: More intuitive behavior for Cargo Kani. Also helps with building dependencies to hard-code linking

Link to relevant documentation (Rust reference, Nomicon, RFC): "https://doc.rust-lang.org/cargo/commands/cargo-test.html"

Test case:

```bash
git clone https://github.com/YoshikiTakashima/kani.git
cd kani
git checkout yoshi-proptest-primitive
git checkout eac76a7e -- library/proptest
cargo clean; cargo build --workspace

# workspaces
cd library/proptest
cargo kani --only-codegen
ls # shows library/proptest/target, not in the right workspace

# --manifest-path
cp Cargo.toml Cargo.test.toml
cargo kani --only-codegen --manifest-path=Cargo.test.toml
```

**Comment by YoshikiTakashima** [comment]
`cargo-kani` already supports `--target_dir`. This can be used to
simulate the workspace feature. Focus on `--manifest-path`.

**Comment by weaversa** [comment]
Sorry to dredge this up -- it would be nice for `cargo kani` to have parity on some common `cargo test` flags such as `--manifest-path`.

**Comment by tedinski** [comment]
Assess fails to build several packages with a message like this:

```
error: There are multiple `serde_json` packages in your project, and the specification `serde_json` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  file:///home/ubuntu/top-100-experiment/json#serde_json@1.0.91
  https://github.com/rust-lang/crates.io-index#serde_json@1.0.91
```

These result from odd configurations of cargo workspaces: it seems there's both a local package and a dependency on the crates.io package of that name. Using `cargo build -p serde_json` apparently doesn't prioritize the local version.

If Kani supported `--manifest-path` this would be immediately resolved. Tagging this as relevant to assess development.
