### ISSUE TITLE
Add E2E concrete playback tests

### ISSUE THREAD

**Issue by sanjit-bhat** [model-checking/kani#1441]
See title. This involves adding a new `compiletest` mode for these kinds of tests.

**Comment by sanjit-bhat** [comment]
I'm working on this issue right now.

**Comment by celinval** [comment]
I believe @adpaco-aws added an option to run scripts as part of compiletest: https://github.com/model-checking/kani/pull/2102. So we could just write a few e2e tests using this infrastructure. We really need to add tests that cover adding tests in place.

**Comment by jaisnan** [comment]
https://github.com/model-checking/kani/pull/2353 Adds an E2E unit test that also runs the generated unit test to get the output. (The test for generating the unit test is already present in the UI section of the regression tests).
