### ISSUE TITLE
Mechanism to safely enable unsound experimental features

### ISSUE THREAD

**Issue by danielsn** [model-checking/kani#1493]

**Comment by tedinski** [comment]
FWIW I think a runtime compile flag is reasonable, I'm not sure we'd want to gate this so hard it depends on building kani yourself to use?

**Comment by danielsn** [comment]
You mean like `kani --enable-unsound --foo`? Rather than making it a `cfg` feature?

**Comment by tedinski** [comment]
I'm not sure exactly what you mean by `cfg` feature, but if it'd require a special build of Kani to use, I think that's too much
