### ISSUE TITLE
Add hooks for pre and post conditions in function contracts.

### ISSUE THREAD

**Issue by monal** [model-checking/kani#1501]
Add hooks to replace `precondition(x)` and `postcondition(x)` as `assume(x)` or `assert(x)` statements. If a function contract is being enforced, `precondition(x)` gets converted to `assume(x)` and `postcondition(x)` gets converted to `assert(x)`.  If a function is being replaced by its contract, `precondition(x)` gets converted to `assert(x)` and `postcondition(x)` to `assume(x)`.

**Comment by celinval** [comment]
This is no longer in the scope of the contracts work.
