### ISSUE TITLE
Add ability to auto-remove generated concrete playback test cases

### ISSUE THREAD

**Issue by sanjit-bhat** [model-checking/kani#1508]
See title. This would improve the user experience if we consider generated test cases to be short-lived. We could either remove all generated test cases or only test cases without a certain label.

This could be done through something like a `TMP` extension to the unit test function name, or a `[kani::short_lived]` attribute on the unit test. If we use an attribute, that might also allow us to specify details about the configurations used during symbolic execution. That way, we can make sure those same configurations are being used during concrete playback.

**Comment by jaisnan** [comment]
Implementing an auto-removing feature and adding an attribute seems excessive for an action as trivial as deleting a test. Imo it should be best left to the user whether to delete a unit test or not and if they decide to delete it, deleting it is already trivial enough.
