### ISSUE TITLE
Workspaces and Features

### ISSUE THREAD

**Issue by YoshikiTakashima** [model-checking/kani#1510]
Requested feature: Ability to deal with `--workspaces` and `Cargo.toml` features 
Use case: Potential customer code (see prost below) contain workspaces.
Link to relevant documentation (Rust reference, Nomicon, RFC): https://doc.rust-lang.org/cargo/reference/manifest.html

Test case: https://github.com/informalsystems/prost

**Comment by tedinski** [comment]
BTW I'd add the same flags as `cargo build`

So `--workspace` and `--all-features` looks like

**Comment by YoshikiTakashima** [comment]
@tedinski Agreed. `cargo kani` should look very similar to `cargo test`

**Comment by YoshikiTakashima** [comment]
@tedinski Shall we change these flags in the compiletest to add these flags when running?
