### ISSUE TITLE
Support logical implication in function contract clauses.

### ISSUE THREAD

**Issue by monal** [model-checking/kani#1547]
Requested feature:
Support the implication operator `=>` in the `ensures` and `requires` clauses of function contracts.

Use case:
This will allow Kani users to specify richer pre and post conditions in their contracts.

Potential solution: Inline them as `if-else` statements during macro expansion.

Test case:

```rust
#[kani::proof]
#[kani::ensures((x < 0) => (ret == -x))]
#[kani::ensures((x >= 0) => (ret == x))]
fn absolute_val(x: i32) -> i32 {
    if (x < 0) {
       -x 
    } else {
        x
    }
}
```

**Comment by celinval** [comment]
We're not planning to add new syntax inside contracts for now. Please feel free to reopen if you disagree.
