### ISSUE TITLE
Support quantifiers in function contract clauses.

### ISSUE THREAD

**Issue by monal** [model-checking/kani#1549]
Requested feature: Support existential and universal quantifiers in the `requires` and `ensures` clauses of function contracts. This would be especially useful to write specifications on vectors.

For example, 
`#[kani::ensures(forall(|i: usize| -> bool {(0 <= i < vec.len()) => (vec[i] > 0)})]`
`#[kani::ensures(exists(|x: i32| -> bool {x == ret})]`

**Comment by JustusAdam** [comment]
Now a duplicate of #2546
