### ISSUE TITLE
Thread local statics is currently unimplemented

### ISSUE THREAD

**Issue by nchong-at-aws** [model-checking/kani#157]
Requested feature: Thread local statics
Use case: Firecracker vmm crate
https://github.com/firecracker-microvm/firecracker/blob/main/src/vmm/src/vstate/vcpu/mod.rs#L123
Link to relevant documentation (Rust reference, Nomicon, RFC):
https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/mir/enum.Rvalue.html#variant.ThreadLocalRef
https://doc.rust-lang.org/std/macro.thread_local.html
https://doc.rust-lang.org/std/thread/struct.LocalKey.html
Is this a breaking change?
No

Test case:
```rust
thread_local! {
    static FOO: u32 = 42;
}

fn main() {
    FOO.with(|v| assert!(*v == 42));
}
```

**Comment by fzaiser** [comment]
This is shows up when compiling tokio. It should not be too difficult to support since Kani is single-threaded.
