### ISSUE TITLE
Error when using `any()` in Kani library: `kani::any_raw_internal` missing

### ISSUE THREAD

**Issue by fzaiser** [model-checking/kani#1604]
When adding a call to `kani::any()` in the Kani library and running a proof harness, using `kani::any()` at the same type, then we get the following error:

```
Check 1: _ZN4kani16any_raw_internal17hd6dc2650eb3dcd77E.1
         - Status: FAILURE
         - Description: "Function `kani::any_raw_internal` with missing definition is unreachable"
         - Location: Unknown file in function kani::any_raw_internal
```

Reproducing example here: https://github.com/model-checking/kani/compare/main...fzaiser:kani:any-raw-internal

**Comment by tedinski** [comment]
Ah, so it gets monomorphized in the `kani` library, the next crate sees it doesn't need to emit it's own monomorphized code, and we suffer from not linking a `kani` `symtab`?

**Comment by tedinski** [comment]
Is this now fixed @celinval ?

**Comment by celinval** [comment]
Yes. This should no longer be a problem. @fzaiser I'm closing this issue but feel free to open it if you bump into a similar problem. Thanks!
