### ISSUE TITLE
Add `--pointer-check` to `goto-instrument --drop-unused-functions` call

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#1621]
As pointed out by @tautschnig here (https://github.com/diffblue/cbmc/issues/6983#issuecomment-1172020654), we should add `--pointer-check` while droping unused functions to ensure that CBMC fails the verification if it cannot find a suitable pointer for a function call.

**Comment by celinval** [comment]
@tautschnig Just double checking, this is no longer needed, right?

That said, do you still recommend enabling all checks before invoking `goto-instrument --drop-unused-functions`?

**Comment by tautschnig** [comment]
My apologies for the delay: yes, this should no longer be necessary. Also, I don't immediately see a reason as to why you'd need to enable checks before `--drop-unused-functions`.

**Comment by celinval** [comment]
No worries! Thank you.
