### ISSUE TITLE
Use Clap Derive API instead of Builder API in `kani-compiler`

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#1647]
`kani-compiler` parser could use a bit of cleaning. We should use Clap Derive API to keep it cleaner and similar to `kani-driver` logic.

**Comment by tedinski** [comment]
FYI, I had a branch that did this. Clap 3 sad semantic breaking changes that meant it didn't eagerly parse short options anymore, breaking kani-compiler.

**Comment by tedinski** [comment]
Oh, wow it's seen progress (maybe? haven't evaluated yet) just yesterday!

https://github.com/clap-rs/clap/issues/3880

**Comment by celinval** [comment]
Yeah, it would be nice to move both parsers to a newer version of clap. The APIs are much nicer now.

**Comment by celinval** [comment]
Maybe we should get rid of the queries all together. We can reintroduce them once we are ready to adopt Salsa.
