### ISSUE TITLE
[March] Github Actions deprecating Ubuntu 18.04 runner

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#1667]
We need to build linux binaries on an older distro, in order to not pin too-new glibc symbols in our binaries. (We need this for CBMC, too, so perhaps should talk to them about it...)

rust-analyzer switched to using `container` to run on a newer OS image, but build within an older OS container: https://github.com/rust-lang/rust-analyzer/pull/13214/files

I was hoping that'd work, seems to work for them!

We should do something similar. Probably with CentOS 7 since that has a longer support lifespan.

**Comment by tedinski** [comment]
The extended date for deprecation is now April 1: https://github.com/actions/runner-images/issues/6002

**Comment by tedinski** [comment]
FYI: Building on Ubuntu 20.04 would produce binaries that I believe won't work on e.g. AL2. Hence the need for building on something like CentOS 7.

**Comment by zhassan-aws** [comment]
Raising the priority of this issue since Ubuntu 18.04 will no longer be supported on Apr 1 (i.e. less than 4 weeks!).
