### ISSUE TITLE
Concrete playback panics if `rustfmt` fails (modifies source code anyway)

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#1680]
I tried this code: The rectangle example in [`tests/cargo-kani/rectangle-example`](https://github.com/model-checking/kani/tree/main/tests/cargo-kani/rectangle-example)

using the following command line invocation:

```
cargo kani --harness stretched_rectangle_can_hold_original --enable-unstable --concrete-playback=inplace
```

with Kani version: 0.10.0 - commit [a2ecd4b9de45404bb141e4bf98e6f9740761bf75](https://github.com/model-checking/kani/commit/a2ecd4b9de45404bb141e4bf98e6f9740761bf75)

I expected to see this happen: Kani modifies the source code and exits gracefully (even if `rustfmt` failed)

Instead, this happened: Kani modifies the source code but reports an panic when calling `rustfmt`
```
INFO: Parsing concrete values from property `rectangle::verification::stretched_rectangle_can_hold_original.assertion.1` with description `assertion failed: larger.can_hold(&original)`.
INFO: Now modifying the source code to include the concrete playback unit test `kani_concrete_playback_stretched_rectangle_can_hold_original_14492733239164819185`.
Unrecognized option: 'unstable-features'
thread 'main' panicked at 'Failed to modify source code: Failed to rustfmt modified source code

Caused by:
    rustfmt exited with status exit status: 1', kani-driver/src/concrete_playback.rs:76:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by YoshikiTakashima** [comment]
Note for replication: use `alias rustfmt='exit 1'`
