### ISSUE TITLE
specify a MSRV/rust-version in kani-verifier

### ISSUE THREAD

**Issue by camshaft** [model-checking/kani#1703]
Requested feature: Having a MSRV/rust-version when installng `kani-verifier` would indicate to the user they need a more recent rust version
Link to relevant documentation (Rust reference, Nomicon, RFC): https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field

Test case:

```shell
$ cargo +1.57.0 install --locked kani-verifier
    Updating crates.io index
error: failed to download `kani-verifier v0.10.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `~/.cargo/registry/src/github.com-1ecc6299db9ec823/kani-verifier-0.10.0/Cargo.toml`

Caused by:
  feature `strip` is required

  The package requires the Cargo feature called `strip`, but that feature is not stabilized in this version of Cargo (1.57.0 (b2e52d7ca 2021-10-21)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-strip-option for more information about the status of this feature.
```

**Comment by tedinski** [comment]
Looks like that feature was stabilized in Rust 1.58 https://releases.rs/docs/released/1.58.0/ (January 2022)

**Comment by tedinski** [comment]
Unfortunately, cargo appears to check this feature before it checks MSRV, the error message does not change with an MSRV added.

Or at least, that's the cast when testing locally with `cargo +1.57.0 install --path .`

**Comment by tedinski** [comment]
Further, removing `strip = "debuginfo"` balloons both binary's sizes from 700k to 4400k, and gains us very little. We're edition 2021, which requires rust 1.56. There's a narrow window of two Rust versions there.

I'm going to close this since there is at least a reasonable error message suggesting a newer version of cargo/rust, and I'm not sure there's a worthwhile change we can make here.
