### ISSUE TITLE
Print out current task and timestamp for better user experience

### ISSUE THREAD

**Issue by toidiu** [model-checking/kani#1713]
Requested feature:
Since a kani run can take very long/never finish it would be good to have user feedback for better user experience.

The following is an output that I see:

```
Runtime Symex: 4.16623s
size of program expression: 95935 steps
slicing removed 51663 assignments
Generated 9089 VCC(s), 4647 remaining after simplification
Runtime Postprocess Equation: 0.0598963s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.426362s
Running propositional reduction
Post-processing
Runtime Post-process: 103.944s
          -------- (doing CBMC verification but no indication)
```

I would be good to have a clue what the tool is doing. I would like the current step to be printed out and an updated timestamp:
```
...
Running propositional reduction
Post-processing
Runtime Post-process: 103.944s
CBMC verifying ... 30s
CBMC verifying ... 31s
CBMC verifying ... 32s
```

**Comment by celinval** [comment]
That totally makes sense. Thanks for the suggestion!

**Comment by rahulku** [comment]
@toidiu Thank you for making this request. Makes complete sense. Our general reporting is currently something we are going to redo. I am going to link this one into #1690 for tracking purposes. 

Before I take any other action, I want to understand your use case and scenario a bit better. How are you using the tool? Why is this output important to you?

**Comment by toidiu** [comment]
> How are you using the tool? Why is this output important to you?

This is feedback related to the UX of the kani tool when developing the proof not CI usage.

If the kani execution takes a long time to complete, the lack of feedback makes it seem like kani is stuck and not making any progress. Feedback gives the developer some indication that kani is infact not stuck and just taking a long time to complete.

**Comment by rahulku** [comment]
Thank you. I will close this out in lieu of #1690 which is tracking the larger piece of work here.
