### ISSUE TITLE
Kani verification takes forever and memory usage exploded

### ISSUE THREAD

**Issue by hiroki-chen** [model-checking/kani#1727]
Hi, dear contributors, thank you for your efforts to make such a wonderful tool!

I am recently considering using Kani to do verification for a personal research project, so I tried it on a few small test cases. However, I found that some of the test cases would take forever to verify, and the memory usage exploded too (it caused OOM).

A sample typestate test:

```rust
mod typestate;

#[cfg(feature = "kani")]
#[kani::proof]
fn test() {
    let buf = [0u8; typestate::DEFAULT_BLOCK_LEN * typestate::DEFAULT_CHUNK_LEN];
    let key = [0x90u8; typestate::DEFAULT_BLOCK_LEN * typestate::DEFAULT_CHUNK_LEN];
    
    // These two asserts work just fine.
    assert_eq!(buf.len(), typestate::DEFAULT_BLOCK_LEN * typestate::DEFAULT_CHUNK_LEN);
    assert_eq!(key.len(), typestate::DEFAULT_BLOCK_LEN * typestate::DEFAULT_CHUNK_LEN);

    if let Ok(data) = typestate::DataState::<typestate::InvalidData>::new(true) {
        // Kani cannot verify this.
        assert_eq!(
            data.len(),
            typestate::DEFAULT_BLOCK_LEN * typestate::DEFAULT_CHUNK_LEN
        );
    }
}

```

The `typestate.rs` can be found [here](https://github.com/hiroki-chen/Rust-Learning/blob/master/Typestate/src/typestate.rs). The above code cannot be properly verified (it never ends, in fact).

Command:
```shell
cargo kani --all-features --harnesses test
```

Some output:
```shell
warning: Found the following unsupported constructs:
             - drop_in_place for drop_unimplemented__RINvNtCs3J1j0Igb0Sc_4core3ptr13drop_in_placeNtNtNtCsewsc74TVMT1_3std2io5error5ErrorECs88wozbZ9mN_4rand (1)
         
         Verification will fail if one or more of these constructs is reachable.
         See https://model-checking.github.io/kani/rust-feature-support.html for more details.

warning: `kani-playground` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
```

I wonder if this is caused by some external dependencies like `rand` or `zeroize`? It seems that Kani will try to perform verification on the compiled code, so it is also trying to verify external dependencies. I wonder if there is a way (or will be) we can just "trust" external crates like `creusot` or `prusti` does? Like this:

```rust
#[extern_spec]
impl std::vec::Vec {
    #[trusted]
    pub fn len(&self) -> usize;
}
```

Or did it happen due to some unsupported features?

Thank you for your time!

**Comment by zhassan-aws** [comment]
Hi @hiroki-chen. Thanks for the bug report. I wasn't able to run the test, but one common cause of non-termination is not setting an unwind value. Can you try adding an unwind annotation e.g.:
```
#[kani::unwind(5)]
```
and rerunning?

Regarding trusting external dependencies, there is an ongoing project for adding support for function contracts, but it is not ready yet.

**Comment by hiroki-chen** [comment]
@zhassan-aws Thank you for your reply!

I tried to add `#[kani::unwind(5)]` to the testing function, and it worked, but the verification failed (but the assertion should hold). During verification, Kani generated a lot of undetermined information when it tried to verify `core::ptr`.

```shell
Check 3176: core::mem::replace::<usize>.precondition_instance.6
         - Status: UNDETERMINED
         - Description: "memcpy destination region writeable"
         - Location: ../.rustup/toolchains/nightly-2022-08-30-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:1310:9 in function core::mem::replace::<usize>
SUMMARY:
 ** 1 of 3177 failed (3176 undetermined)
Failed Checks: Function `std::sys::unix::thread_local_dtor::register_dtor` with missing definition is unreachable
```

I used the `rand` crate, which generated a `thread_local` seed for random numbers. I guess that is may be the root cause?

---
> Regarding trusting external dependencies, there is an ongoing project for adding support for function contracts, but it is not ready yet.

Glad to hear this! I suppose that function contracts seem to be a more natural solution :)

Thank you very much for making Kani!

**Comment by zhassan-aws** [comment]
The failure is due to a [bug ](#1213 )in Kani: currently, it does not link the standard library (`std`), and it ends up replacing some `std` functions, e.g. the one you encountered (`std::sys::unix::thread_local_dtor::register_dtor`) with `assert(false)`. This would cause verification to fail if the function is reachable from the harness.

We're currently working on a fix for this issue. The workaround in the meantime is to delete/replace the code that ends up calling this `std` function (most likely `thread_rng`?).

**Comment by zhassan-aws** [comment]
With this diff:
```
diff --git a/Typestate/src/main.rs b/Typestate/src/main.rs
index fb0063b..36e9826 100644
--- a/Typestate/src/main.rs
+++ b/Typestate/src/main.rs
@@ -4,13 +4,15 @@ extern crate zeroize;

 mod typestate;

+#[kani::proof]
+#[kani::unwind(133)]
 fn main() {
     let buf = [0u8; typestate::DEFAULT_BLOCK_LEN * typestate::DEFAULT_CHUNK_LEN];
     let key = [0x90u8; typestate::DEFAULT_BLOCK_LEN * typestate::DEFAULT_CHUNK_LEN];
     let data = typestate::DataState::<typestate::InvalidData>::new(true).unwrap();
     println!("[+] Encrypted data: {:02x?}", data);
     let encrypted_data = data.ready().expect("OKOK");
-    encrypted_data.save_to_file("./data.bin").expect("OKOK");
+    //encrypted_data.save_to_file("./data.bin").expect("OKOK");
     let decrypted_data = encrypted_data.decrypt(&key).expect("OKOK");
     println!("[+] Decrypted data: {:02x?}", decrypted_data);
 }
diff --git a/Typestate/src/typestate.rs b/Typestate/src/typestate.rs
index 779bfaf..e5e52d0 100644
--- a/Typestate/src/typestate.rs
+++ b/Typestate/src/typestate.rs
@@ -102,9 +102,9 @@ impl DataState<InvalidData> {
     pub fn new(should_fill_random_data: bool) -> DataResult<DataState<InvalidData>> {
         let mut inner: Option<Vec<u8>> = None;
         if should_fill_random_data {
-            let mut rng = thread_rng();
-            let mut bytes = [0u8; DEFAULT_BLOCK_LEN * DEFAULT_CHUNK_LEN];
-            rng.fill_bytes(&mut bytes);
+            //let mut rng = thread_rng();
+            let mut bytes: [u8; DEFAULT_BLOCK_LEN * DEFAULT_CHUNK_LEN] = kani::any();
+            //rng.fill_bytes(&mut bytes);
             inner = Some(bytes.to_vec());
         }
```
verification passes:
```


SUMMARY:
 ** 0 of 1546 failed

VERIFICATION:- SUCCESSFUL

Verification Time: 21.231556s
```

**Comment by hiroki-chen** [comment]
> With this diff:
> 
> ```
> diff --git a/Typestate/src/main.rs b/Typestate/src/main.rs
> index fb0063b..36e9826 100644
> --- a/Typestate/src/main.rs
> +++ b/Typestate/src/main.rs
> @@ -4,13 +4,15 @@ extern crate zeroize;
> 
>  mod typestate;
> 
> +#[kani::proof]
> +#[kani::unwind(133)]
>  fn main() {
>      let buf = [0u8; typestate::DEFAULT_BLOCK_LEN * typestate::DEFAULT_CHUNK_LEN];
>      let key = [0x90u8; typestate::DEFAULT_BLOCK_LEN * typestate::DEFAULT_CHUNK_LEN];
>      let data = typestate::DataState::<typestate::InvalidData>::new(true).unwrap();
>      println!("[+] Encrypted data: {:02x?}", data);
>      let encrypted_data = data.ready().expect("OKOK");
> -    encrypted_data.save_to_file("./data.bin").expect("OKOK");
> +    //encrypted_data.save_to_file("./data.bin").expect("OKOK");
>      let decrypted_data = encrypted_data.decrypt(&key).expect("OKOK");
>      println!("[+] Decrypted data: {:02x?}", decrypted_data);
>  }
> diff --git a/Typestate/src/typestate.rs b/Typestate/src/typestate.rs
> index 779bfaf..e5e52d0 100644
> --- a/Typestate/src/typestate.rs
> +++ b/Typestate/src/typestate.rs
> @@ -102,9 +102,9 @@ impl DataState<InvalidData> {
>      pub fn new(should_fill_random_data: bool) -> DataResult<DataState<InvalidData>> {
>          let mut inner: Option<Vec<u8>> = None;
>          if should_fill_random_data {
> -            let mut rng = thread_rng();
> -            let mut bytes = [0u8; DEFAULT_BLOCK_LEN * DEFAULT_CHUNK_LEN];
> -            rng.fill_bytes(&mut bytes);
> +            //let mut rng = thread_rng();
> +            let mut bytes: [u8; DEFAULT_BLOCK_LEN * DEFAULT_CHUNK_LEN] = kani::any();
> +            //rng.fill_bytes(&mut bytes);
>              inner = Some(bytes.to_vec());
>          }
> ```
> 
> verification passes:
> 
> ```
> 
> 
> SUMMARY:
>  ** 0 of 1546 failed
> 
> VERIFICATION:- SUCCESSFUL
> 
> Verification Time: 21.231556s
> ```

Thank you! I tried to disable calling to`thread_rng()`, and now Kani wouldn't complain anything, and the verification passed too.

**Comment by zhassan-aws** [comment]
Closing this issue as it seems to be resolved. Feel free to reopen if you're still having issues.
