### ISSUE TITLE
Kani doesn't provide an optional flag for alternative install path

### ISSUE THREAD

**Issue by weaversa** [model-checking/kani#1735]
Requested feature: cargo-kani setup to install to `$KANI_HOME` if set, and do what it does now (install to `$HOME/.kani`) otherwise.

Use case: I'm installing Kani in a docker container for use in a containerized development environment (Coder). The environment quashes the $HOME directory upon import of the container, so a pre-installed Kani at the default location for Kani (`$HOME/.kani`) doesn't exist after the container is launched.

Thank you!

**Comment by adpaco-aws** [comment]
Thanks @weaversa for the feature request!

Sounds good. Please allow me to edit the title so it's more descriptive.

**Comment by adpaco-aws** [comment]
@weaversa the last version contains the requested feature as you described it. Please let us know if something doesn't work they way you expected.

**Comment by weaversa** [comment]
Thank you!
