### ISSUE TITLE
Performance regression (possibly involving `Result`)

### ISSUE THREAD

**Issue by aaronbembenek-aws** [model-checking/kani#1766]
I encountered a 100x slowdown (from 3 seconds to 700+ seconds) on a Firecracker proof I've been working on (used as an example in #1723). The offending commit is the toolchain upgrade to nightly-2022-09-13 (07092de).

I suspect that the reason is that `Result` used to be represented as a struct, but is now represented as a union. Consider this function:

```rust
fn do_something() -> Result<u32, &'static str> {
    if kani::any() {
        Ok(42)
    } else {
        Err("woops")
    }
}
```

Before, the GotoC signature was:

```
struct std::result::Result<u32, &str> do_something(void);
```

Afterwards, the GotoC signature was:

```
union std::result::Result<u32, &str> do_something(void);
```

The toolchain upgrade involved changes to the niche optimization, so it could be related to that.

**Comment by aaronbembenek-aws** [comment]
I believe that this issue has been resolved with changes to CBMC, but waiting on #1962 to confirm.

The Firecracker proof that witnessed this regression is available [here](https://github.com/aaronbembenek-aws/kani/tree/firecracker-stubbing-demo/firecracker-stubbing-demo). With the `METRICS` statements in the `parse_put_vsock` function enabled (they're commented out by default), running the proof harness with Kissat used to take ~170 seconds before the regression.

**Comment by tautschnig** [comment]
Do you strictly need to use Kissat? Would CBMC built with CaDiCaL as solver not have fairly similar performance? (I would actually expect Kani's performance with an external SAT solver to be pretty poor, because it will repeatedly have to solve a very similar problem, but will always do so from scratch.)

**Comment by aaronbembenek-aws** [comment]
Using CBMC built with CaDiCaL should suffice. I've run into some linking issues when trying to build this, but I'll post results once I have them. I did try CBMC built with glucose, and it takes 470 seconds (about the same as using CBMC's default build).

**Comment by tautschnig** [comment]
> Using CBMC built with CaDiCaL should suffice. I've run into some linking issues when trying to build this, but I'll post results once I have them. I did try CBMC built with glucose, and it takes 470 seconds (about the same as using CBMC's default build).

Let me know what those issues are, CaDiCaL builds ought to work fine out of the box.

**Comment by aaronbembenek-aws** [comment]
Good news: things are quite fast using CBMC built with CaDiCAL (~20s), so we can close this issue.

> Let me know what those issues are, CaDiCaL builds ought to work fine out of the box.

I don't think there was anything CBMC specific here - just common problems with trying to build C++ projects on Mac that were resolved by explicitly installing a compiler with Homebrew instead of using the system one.
