### ISSUE TITLE
symbol lookup error after kani update

### ISSUE THREAD

**Issue by zpzigi754** [model-checking/kani#1787]
If I've updated kani by following [the-installation-guide](https://model-checking.github.io/kani/install-guide.html), it causes a symbol error like the below when the version is over 0.8. (Kani works well with version 0.8 or lower versions. Also, it works well when I've manually installed it).

```
/home/xxx/.kani/kani-0.10.0/bin/kani-compiler: symbol lookup error: /home/xxx/.kani/kani-0.10.0/bin/../toolchain/lib/librustc_driver-e70f935d0865b673.so: undefined symbol: _ZN9hashbrown3raw11Fallibility17capacity_overflow17h52b24f50adb3934dE
```

The symbol error occurred when I've used the below commands for the installation.
```
cargo install --locked kani-verifier
cargo-kani setup
```
or 
```
cargo install --locked kani-verifier --version <VERSION>
cargo-kani setup
```

My ubuntu version is like the below.
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

I tried this code:

```rust
// File: test.rs
#[kani::proof]
fn main() {
    assert!(1 == 2);
}
```

using the following command line invocation:

```
cargo kani
```

**Comment by tedinski** [comment]
This should be:

* #1709 

Switching to stable rust as default toolchain should resolve it, and next week's release (0.13) should fix that bug for good.

**Comment by zpzigi754** [comment]
Thanks a lot for the help!
Good to hear that 0.13 would fix this problem in the beginning. I will try both suggestions.

**Comment by zpzigi754** [comment]
I've confirmed that the error occurred because my `LD_LIBRARY_PATH` was pointing to rust's nightly library. 
After removing it, I could use the latest kani with the installation guide.

**Comment by celinval** [comment]
Awesome! Thanks for checking it out. I'll close this issue for now but feel free to re-open if you face a similar problem again. Cheers!
