### ISSUE TITLE
Assess report is miscounting number of crates in a workspace 

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#1799]
I tried the code from this workspace: https://github.com/model-checking/kani/tree/main/tests/cargo-ui/ws-integ-tests

using the following command line invocation:

```
cargo kani  --legacy-linker assess
```

with Kani version: 0.13

I expected to see this happen: The number of crates analyzed should be 4 (maybe 5 if you include `std`).

Instead, this happened: It reported 9 different crates.

**Comment by tedinski** [comment]
Related #1758
