### ISSUE TITLE
Kani's slow tests are failing

### ISSUE THREAD

**Issue by fzaiser** [model-checking/kani#1818]
... and have been failing for a while: https://github.com/model-checking/kani/actions/workflows/slow-tests.yml

Cc @danielsn because he suggested them.

**Comment by fzaiser** [comment]
The relevant line in the logs is `CBMC failed with status 137`, indicating an out-of-memory error. They started failing on 28 September. The only relevant commit on the day before seems to be #1717 ("Build custom sysroot with --always-encode-mir on").
@celinval Do you know what the reason of this could be? I'm observing something similar in the CI tests for #1659.

**Comment by celinval** [comment]
Hi @fzaiser, #1717 fixed the issue with missing symbols from the standard library. The downside is that the goto program we generate can be much bigger, which may slow down the verification or cause cbmc to run out of memory.

**Comment by fzaiser** [comment]
The tests started passing again a few days ago, probably because of https://github.com/model-checking/kani/pull/1941. They also run much quicker (~100 seconds instead of minutes) now! :tada:
