### ISSUE TITLE
0.14 tar.gz file not found on the first execution of kani binary

### ISSUE THREAD

**Issue by zpzigi754** [model-checking/kani#1834]
I've manually built the latest kani (6ef19f2). On the first execution of `cargo-kani` or `kani`, it fails to download the related `tar.gz` file.

```
$ ./kani
[0/5] Running Kani first-time setup...
[1/5] Ensuring the existence of: /home/xxx/.kani/kani-0.14.0
[2/5] Downloading Kani release bundle: kani-0.14.0-x86_64-unknown-linux-gnu.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download Kani release bundle

Caused by:
    Failed command: curl -sSLf -o /home/xxx/.kani/kani-0.14.0-x86_64-unknown-linux-gnu.tar.gz https://github.com/model-checking/kani/releases/download/kani-0.14.0/kani-0.14.0-x86_64-unknown-linux-gnu.tar.gz
```

It seems that 0.14 is not uploaded in https://github.com/model-checking/kani/releases/ and crates-io registry.

**Comment by zhassan-aws** [comment]
Hi @zpzigi754. Thanks for the report. The 0.14 release is not out yet. We're hoping to release it in the next 24 hours.

If you've manually built Kani from source, then you should point to the executables that are inside the `target` directory of the Kani source tree, e.g.:
```
$ ls target/*/*kani
target/debug/cargo-kani  target/debug/kani
```
Those executables would run directly without the need to download anything.

**Comment by zpzigi754** [comment]
> If you've manually built Kani from source, then you should point to the executables that are inside the `target` directory of the Kani source tree, e.g.:
> 
> ```
> $ ls target/*/*kani
> target/debug/cargo-kani  target/debug/kani
> ```
> 
> Those executables would run directly without the need to download anything.

Thanks for the answer.

On the execution of that guided path, I've encountered the following error.
```
~/kani/target/debug$ ./cargo-kani --version
Error: Running a release-only executable, cargo-kani, from a development environment. This is usually caused by PATH including 'target/release' erroneously.
```

After commenting out [the related line](https://github.com/model-checking/kani/blob/main/src/lib.rs#L44) in the source code and setting up the sysroot manually by locating the generated `bin`, `legacy-lib`, `lib`, `library` and putting `rust-toolchain-version` with `nightly-2022-10-24-x86_64-unknown-linux-gnu`, I've encountered the following error message (with this manual sysroot setup, 0.13 works).
```
~/kani/target/debug$ ./cargo-kani
Error: Failed to get cargo metadata.

Caused by:
    `cargo metadata` exited with an error: error: override toolchain 'nightly-2022-10-24-x86_64-unknown-linux-gnu
    ' is not installed: the RUSTUP_TOOLCHAIN environment variable specifies an uninstalled toolchain
```

I am not sure why this error occurred even though I have `nightly-2022-10-24-x86_64-unknown-linux-gnu`, as can be seen in `rustup show`.
```
$ rustup show
installed toolchains
--------------------
nightly-2022-10-24-x86_64-unknown-linux-gnu
```


When I've used the `kani-driver` directly with the manual sysroot or `cargo-kani` in the `./scripts` which does not seem to require setting the sysroot, the symptom is a bit different (type conflict). 

```
// File: main.rs
#[kani::proof]
fn main() {
    assert!(1 == 2);
}
```

```
$ cargo-kani (or kani-driver main.rs)
error: conflicting types for variable '__CPROVER_architecture_long_long_int_width'
old definition in module 'kani_lib' file <builtin-architecture-strings> line 7
const signed int
new definition in module '' 
integer
error: conflicting types for variable '__CPROVER_architecture_short_int_width'
old definition in module 'kani_lib' file <builtin-architecture-strings> line 6
const signed int
new definition in module '' 
integer
error: conflicting types for variable '__CPROVER_architecture_char_width'
old definition in module 'kani_lib' file <builtin-architecture-strings> line 5
const signed int
new definition in module '' 
integer
...
typechecking main failed
Error: goto-cc exited with status exit status: 1
```

I guess that there is some compatibility issue in (https://github.com/model-checking/kani/pull/1811).

**Comment by celinval** [comment]
Hi @zpzigi754, when building from source, I recommend making sure that the `scripts/` folder is in your path. Running `cargo-kani` and `kani` directly from the `target` folder might not do what you expect. These two binaries are just proxies that will download the binaries that were released, not the binaries you just built.

**Comment by zpzigi754** [comment]
> Hi @zpzigi754, when building from source, I recommend making sure that the `scripts/` folder is in your path. Running `cargo-kani` and `kani` directly from the `target` folder might not do what you expect. These two binaries are just proxies that will download the binaries that were released, not the binaries you just built.

Thank you for the recommentation, @celinval. I've noticed late that `(REPO)/scripts/cargo-kani` is different from `(ROPO)/target/debug/cargo-kani` while they have the same name. I will make sure putting `scripts/` in the path.

**Comment by zhassan-aws** [comment]
Closing this bug as Kani 0.14 was released a couple of days ago. Feel free to reopen if you're still running into issues.
