### ISSUE TITLE
Remove `--harness` argument from `kani-compiler`

### ISSUE THREAD

**Issue by aaronbembenek-aws** [model-checking/kani#1841]
The `--harness` argument has been temporarily added to `kani-compiler` to ease initial support for stubbing. We should remove it once the stubbing mechanism can handle multiple harnesses at once.

**Comment by celinval** [comment]
TBH, I don't think we should remove this. Maybe we should pass that option down to the compiler to avoid generating code for harnesses that we don't care about.

Any thoughts?

**Comment by aaronbembenek** [comment]
Seems reasonable to me. I created this issue because I had to add the `--harness` argument to support stubbing, and so figured it'd make sense to remove it once it was no longer necessary for that. If there's a good rationale for keeping it around besides stubbing, I have no problem with that :)

**Comment by celinval** [comment]
Thanks @aaronbembenek, this is an internal detail, so I think we can adapt as we are able to measure cost benefit. My feeling is that once we get rid of symtab2gb and we enable compilation cache, things will change. For now, we might want to keep it.

Maybe let's leave this issue open so we can revisit this decision in the near future.
