### ISSUE TITLE
Figure out missing source location for vtable initializers.

### ISSUE THREAD

**Issue by vecchiot-aws** [model-checking/kani#185]

**Comment by vecchiot-aws** [comment]
https://github.com/vecchiot-aws/rmc/tree/vtable-initialize-location

**Comment by vecchiot-aws** [comment]
Currently blocked; the source locations correctly appear in the XML output, but do not appear in the HTML output.

**Comment by tautschnig** [comment]
Closing as there isn't enough information to see where we still might be missing locations (#3253 does add a locations to some vtable-related expressions).
