### ISSUE TITLE
Allow kani to return EXIT_SUCCESS for empty proof harnesses

### ISSUE THREAD

**Issue by alexgv-aws** [model-checking/kani#1857]
**Feature:** Treat empty harnesses as successes rather than failures, either by default or through a flag. This is helpful to make generic CI checkers that automatically pick up proofs when they exist for a project and ignore them when they don't. As an example, consider that `cargo test` does not fail on an empty harness.

**Current behaviour:** `kani` unconditionally errors out if there's no proof harness.

```
alexgv@mypc:~$ cargo new mwe
     Created binary (application) `mwe` package
alexgv@mypc:~$ cd mwe && cargo kani || echo NONZERO_EXIT
   Compiling mwe v0.1.0 (/home/alexgv/mwe)
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Error: No proof harnesses (functions with #[kani::proof]) were found to verify.
NONZERO_EXIT
```

**Comment by tedinski** [comment]
That seems reasonable to me. I don't think the current behavior was carefully considered.

Anyone object?

**Comment by danielsn** [comment]
That also seems reasonable to me.
