### ISSUE TITLE
Error opening file '(..)/hifitime/target/x86_64-unknown-linux-gnu/debug/deps/cbmc-linked.out'

### ISSUE THREAD

**Issue by ChristopherRabotin** [model-checking/kani#1896]
When using Kani version 0.14.1, it fails to do a harness check:

```
╭─chris@localhost in ~/Workspace/nyx-space/hifitime on 172-fix-formal-verification ✔ (origin/172-fix-formal-verification)
╰$ cargo-kani                                                            
Error opening file '/home/chris/Workspace/nyx-space/hifitime/target/x86_64-unknown-linux-gnu/debug/deps/cbmc-linked.out'
Error: goto-cc exited with status exit status: 1

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: kani_driver::session::KaniSession::run_suppress
   2: kani_driver::call_goto_cc::<impl kani_driver::session::KaniSession>::link_goto_binary
   3: kani_driver::main
   4: std::sys_common::backtrace::__rust_begin_short_backtrace
   5: std::rt::lang_start::{{closure}}
   6: std::rt::lang_start_internal
   7: main
   8: __libc_start_call_main
   9: __libc_start_main@GLIBC_2.2.5
  10: _start

```

The issue happens with Github actions when using the provided Action, cf. https://github.com/nyx-space/hifitime/actions/runs/3466289900/jobs/5789955435 .

I'm really not too sure where to start debugging this, so let me know what I can do to help. This happens on [this commit of hifitime](https://github.com/nyx-space/hifitime/commit/e44444ebd9004e39bcd152ae773e3251cb84245b).

**Comment by celinval** [comment]
Hi @ChristopherRabotin, thank you for reporting the problem. I was able to locally reproduce the issue. Let me see what I can find. Cheers!

**Comment by celinval** [comment]
I believe the root cause here is that we can't handle `rlib` properly. :(

We'll work on a fix and keep you posted.

**Comment by ChristopherRabotin** [comment]
Yes, I have noticed that. However, the first step in the build is to remove
the rlib from Cargo so it doesn't build. The Python interface stuff is
behind a crate feature that is disabled by default.

**Comment by celinval** [comment]
I looked at the workflow you posted, and I believe you currently remove the `cdylib` from the Cargo.toml.

I create a fix that will recognize the `rlib` as a target, but for now you will need to keep the hack to remove the `cdylib` from your `crate-type`. I'll create another issue to also fix that.

**Comment by celinval** [comment]
@ChristopherRabotin I created #1915 to track adding support to `cdylib` crate type.
