### ISSUE TITLE
Standalone `kani` on file without proof harnesses crashes

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#1910]
```
$ kani src/main.rs 
Error: No such file or directory (os error 2)
```

There are two fixes needed here:

1. That error message should be improved. We're not reporting what file was missing.
2. We should (in this situation) be reporting the same "No proof harnesses" result as `cargo kani`. I'm not sure why `kani` isn't producing the `kani-metadata.json` file that was expected (and that's what there's "no such file" for)

**Comment by celinval** [comment]
We skip codegen if there is nothing to generate code for. We could generate an empty metadata file. But I think this might still fail in the `link_goto_binary()`.
