### ISSUE TITLE
Cryptic error when running Kani on a file without a harness

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#1913]
I tried this code:

```rust
// no_harness.rs
pub fn my_api() {
    todo!()
}
```

using the following command line invocation:

```
kani no_harness.rs
```

with Kani version: 0.15.0

I expected to see this happen:  Kani should exit gracefully and print the same message it prints when using `cargo kani`

```
No proof harnesses (functions with #[kani::proof]) were found to verify.
```

Instead, this happened: Kani command failed with the following error:

```
Error: No such file or directory (os error 2)
```

**Comment by zhassan-aws** [comment]
This is a duplicate of https://github.com/model-checking/kani/issues/1910?

**Comment by celinval** [comment]
Yeah, I just noticed that now. I'll close this one.
