### ISSUE TITLE
Inconsistent behavior when functions with parameters are used as harnesses 

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#1919]
Consider the following program:
```rust
#[kani::proof]
fn foo(c: char) {
    assert!(char::from_u32(c as u32).is_some());
}

#[kani::proof]
fn bar() {
    let c = kani::any();
    foo(c);
}
```
When run with:
```
kani entry.rs --harness bar
```
verification succeeds as expected:
```
SUMMARY:
 ** 0 of 67 failed

VERIFICATION:- SUCCESSFUL
```
However, when run with
```
kani entry.rs --harness foo
```
verification fails:
```
SUMMARY:
 ** 1 of 11 failed
Failed Checks: assertion failed: char::from_u32(c as u32).is_some()
 File: "/home/ubuntu/examples/entry.rs", line 3, in foo

VERIFICATION:- FAILED
```
Kani version: 4db1b0964a3

This is caused by not applying the validity constraints on `char` in the `foo` version.

**Comment by zhassan-aws** [comment]
We may want to disallow using functions with parameters as harnesses until we figure out a fix.

**Comment by tedinski** [comment]
Apparently it was not completed, was here:

* https://github.com/model-checking/kani/issues/689

I agree with disallowing them, it's a bug they're allowed presently.
