### ISSUE TITLE
Kani build/analysis failure on ARM macOS

### ISSUE THREAD

**Issue by rod-chapman** [model-checking/kani#1967]
I am trying to reproduce the Kani analysis of s2n-quic, but using an ARM-based macOS laptop.

I have Rust (1.57, stable, and nightly toolchains), Kani 0.16.0 and GCC 12.1.0 (aarch64-apple-darwin) installed.

Running "cargo kani --tests" in s2n-quic-core fails with

```
    Finished test [unoptimized + debuginfo] target(s) in 14.71s
/opt/gcc-12.1.0-aarch64/lib/gcc/aarch64-apple-darwin21/12.1.0/include/stddef.h:432:1: error: syntax error before '__float128'
   __float128 __max_align_f128 __attribute__((__aligned__(__alignof(__float128))));
PARSING ERROR
Error: goto-cc exited with status exit status: 1
```

I don't think that GCC predefines type __float128 on aarch64.

**Comment by celinval** [comment]
Closing this based on @jaisnan comment. @rod-chapman please feel free to reopen this if you are still bumping into the same issue. Thanks!
