### ISSUE TITLE
Question about firecracker blog post

### ISSUE THREAD

**Issue by ranjitjhala** [model-checking/kani#1976]
Dear Kani team - I enjoyed reading your firecracker blog post, thank you!

https://model-checking.github.io/kani-verifier-blog/2022/07/13/using-the-kani-rust-verifier-on-a-firecracker-example.html

But was puzzled by the line

> if we insert an issue such as forgetting a validity check to ensure the third buffer is **read-only**, 
> then Kani reports an error (since in this case it is possible to fail virtio requirement 2.6.4.2 but 
> return a valid Request)

Should that **read-only** be **write-only** (per the state machine?) Looking around in the code for the example, I saw this
check which also seems to indicate that the check is "must be write-only", or did I get something wrong?

https://github.com/model-checking/kani/blob/main/tests/cargo-kani/firecracker-block-example/src/main.rs#L404-L407

Thanks again for this excellent work!

**Comment by adpaco-aws** [comment]
Hey @ranjitjhala , thanks for bringing this to our attention!

I think you're right and that's a mistake. In fact, it's said earlier (when discussing the buffers) that:
> * The third describes a write-only buffer for the device to fill with a status byte indicating whether the request succeeded.

I've submitted a PR to correct this mistake in https://github.com/model-checking/kani-verifier-blog/pull/24 so I can get it reviewed by another member on our team. Many thanks!

**Comment by ranjitjhala** [comment]
Ah yes, good point thanks for the confirmation!

**Comment by adpaco-aws** [comment]
Closing since the post has been updated with the correction. Thank you, @ranjitjhala !
