### ISSUE TITLE
Update rust toolchain version for Kani 0.17

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#1977]
Biweekly update for the rust toolchain version. For Kani 0.17, we will target the nightly-2022-12-04 version.

**Comment by adpaco-aws** [comment]
@fzaiser do you have any idea why this is happening?

**Comment by fzaiser** [comment]
@adpaco-aws No, I don't understand how this function could be missing given that it is defined in the same file as the proof harness.

**Comment by adpaco-aws** [comment]
Regarding the crash (file `main.rs`), I'm noticing significant differences in codegen between stable and nightly.

This can be misleading, because I'm not comparing with the previous nightly version (instead of stable), but in the line leading to the crash I'm getting:
```
        _6 = <impl Future<Output = i32> as Future>::poll(move _7, move _10) -> [return: bb7, unwind: bb22]; // scope 3 at src/main.rs:12:42: 12:48
                                         // mir::Constant
                                         // + span: src/main.rs:12:42: 12:48
                                         // + literal: Const { ty: for<'a, 'b, 'c> fn(Pin<&'a mut impl Future<Output = i32>>, &'b mut Context<'c>) -> Poll<<impl Future<Output = i32> as Future>::Output> {<impl Future<Output = i32> as Future>::poll}, val: Value(<ZST>) }

```
while in the nightly I get:
```
        _6 = <[async block@src/main.rs:12:30: 12:42] as Future>::poll(move _7, move _10) -> [return: bb6, unwind: bb20]; // scope 3 at src/main.rs:12:42: 12:48
                                         // mir::Constant
                                         // + span: src/main.rs:12:42: 12:48
                                         // + literal: Const { ty: for<'a, 'b, 'c> fn(Pin<&'a mut [async block@src/main.rs:12:30: 12:42]>, &'b mut Context<'c>) -> Poll<<[async block@src/main.rs:12:30: 12:42] as Future>::Output> {<[async block@src/main.rs:12:30: 12:42] as Future>::poll}, val: Value(<ZST>) }
```
I will come back to this later.

**Comment by adpaco-aws** [comment]
Maybe [this commit](https://github.com/rust-lang/rust/commit/b5ae4c9629f697034fb93f660202f354f13b74c3) is related, but it's hard to say at this point.

**Comment by zhassan-aws** [comment]
Won't fix as described above.
