### ISSUE TITLE
Regression tests for intrinsics fail on M1 and Intel Macs

### ISSUE THREAD

**Issue by aaronbembenek-aws** [model-checking/kani#1993]
Some Kani regression tests for intrinsics fail when running on an M1 Mac.

I used the following command line invocation:

```
./scripts/kani-regression.sh
```

with Kani 0.16.0 (8527e9c6)

I expected to see this happen: regression tests pass

Instead, this happened: 18 regression tests fail

```
failures:
    [kani] kani/Intrinsics/CopySign/copysignf32.rs
    [kani] kani/Intrinsics/CopySign/copysignf64.rs
    [kani] kani/Intrinsics/Math/Rounding/Ceil/ceilf32.rs
    [kani] kani/Intrinsics/Math/Rounding/Ceil/ceilf64.rs
    [kani] kani/Intrinsics/Math/Rounding/Floor/floorf32.rs
    [kani] kani/Intrinsics/Math/Rounding/Floor/floorf64.rs
    [kani] kani/Intrinsics/Math/Rounding/NearbyInt/nearbyintf32.rs
    [kani] kani/Intrinsics/Math/Rounding/NearbyInt/nearbyintf64.rs
    [kani] kani/Intrinsics/Math/Rounding/RInt/rintf32.rs
    [kani] kani/Intrinsics/Math/Rounding/RInt/rintf64.rs
    [kani] kani/Intrinsics/Math/Rounding/Round/roundf32.rs
    [kani] kani/Intrinsics/Math/Rounding/Round/roundf64.rs
    [kani] kani/Intrinsics/Math/Rounding/Trunc/truncf32.rs
    [kani] kani/Intrinsics/Math/Rounding/Trunc/truncf64.rs
    [kani] kani/Intrinsics/MaxNum/maxnumf32.rs
    [kani] kani/Intrinsics/MaxNum/maxnumf64.rs
    [kani] kani/Intrinsics/MinNum/minnumf32.rs
    [kani] kani/Intrinsics/MinNum/minnumf64.rs
```

The failures are in this form (the exact missing function differs):

```
Failed Checks: undefined function should be unreachable
 File: "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h", line 211, in __inline_isnand
```

**Comment by aaronbembenek-aws** [comment]
Here's the definition of `__inline_isnand` from `math.h`:

```c
__header_always_inline int __inline_isnand(double __x) {                                          
    return __x != __x;                                                                            
}
```

**Comment by aaronbembenek-aws** [comment]
> Here's the definition of `__inline_isnand` from `math.h`:
> 
> ```c
> __header_always_inline int __inline_isnand(double __x) {                                          
>     return __x != __x;                                                                            
> }
> ```

FWIW, on my machine `__header_always_inline` expands to

```c
inline __attribute__ ((__always_inline__))
```

**Comment by tautschnig** [comment]
Could you please attach a zip archive containing the artifacts from running one of these tests with `--keep-temps` and also the output of `--verbose`?

**Comment by aaronbembenek-aws** [comment]
I disabled the intrinsics tests and it turns out a bunch of other tests fail too; for example:

```shellsession
$ kani tests/expected/trait-receiver/receiver_types.rs --harness check_box
...
SUMMARY:
 ** 1 of 330 failed (8 unreachable)
Failed Checks: undefined function should be unreachable
 File: "<built-in-additions>", line 17, in __CPROVER_deallocate
```

The culprit CBMC commit is diffblue/cbmc@da4c6ec463.

Here's a zip archive with the files for this test: [receiver_types.zip](https://github.com/model-checking/kani/files/10232353/receiver_types.zip)

**Comment by aaronbembenek-aws** [comment]
The same tests fail on an Intel Mac when using CBMC 5.72.2 (and pass when using CBMC 5.72.0).

**Comment by tautschnig** [comment]
See my update in #2020: https://github.com/diffblue/cbmc/pull/7453 will fix this bug. Thank you for reporting and bisecting!

**Comment by tautschnig** [comment]
While https://github.com/diffblue/cbmc/pull/7453 fixed one bug, it didn't fully fix the issue. I'll post another bugfix shortly, and can even demonstrate that this was an issue with C code as well, it's not Kani/Rust specific.

**Comment by tautschnig** [comment]
https://github.com/diffblue/cbmc/pull/7475 is the fix on the CBMC side, and I've confirmed that the above regressions now pass on macOS.

**Comment by tautschnig** [comment]
https://github.com/diffblue/cbmc/pull/7453 is now merged.
