### ISSUE TITLE
cdylib target stops all verification

### ISSUE THREAD

**Issue by weaversa** [model-checking/kani#2006]
Kani errors when I add `cdylib` as a build target.

I tried this code:

```rust
[lib]
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]
```

using the following command line invocation:

```
cargo kani
```

with Kani version:

```
warning: Skipped verification of `<program>` due to unsupported crate-type: `cdylib`.
Error: No supported targets were found.
```

Kani should still attempt to verify the `"lib"` target. Instead, I have to modify the `crate-type` to  `crate-type = ["lib"]` for Kani to do any work.

**Comment by weaversa** [comment]
> Hi @weaversa, thanks for reporting this issue. I believe this is the same root cause as #1915. Is this blocking you right now or can you change the crate type locally and keep running Kani?
> 
> Just to give a bit more background, cargo sets different rustc flags according to the library types. For cdylib, the compiler will try to generate a shared library, which we can't handle. We also have no mechanism to skip it yet.

Hi @celinval. I'm ok right now, and I look forward to when this is not an issue. I'm happy to close this in favor of #1915 if you wish.

**Comment by weaversa** [comment]
Our workaround was to add an extra layer to the project. We restructured from (generically):

```
project
  | - Cargo.toml
  | - src
     | - lib.rs
     | - kani_proofs.rs
     | - unit_tests.rs
```

to

```
project
  | - Cargo.toml ([workspace] says "members= ["main", "cdylib"])
  | - main
      | - Cargo.toml
      | - src
         | - lib.rs
         | - kani_proofs.rs
         | - unit_tests.rs
  | - cdylib
      | - Cargo.toml
      | - src
           | - lib.rs (a stub that says 'pub use main::*')
```

**Comment by celinval** [comment]
Sorry that you had to make changes to your project layout. So if you don't mind, let's track this work on #1915.

**Comment by celinval** [comment]
@weaversa I just wanted to let you know that I've pushed a fix for this which shall be included in the next release.

**Comment by weaversa** [comment]
Thank you!
