### ISSUE TITLE
Kani needlessly recompiles everything every time

### ISSUE THREAD

**Issue by Kixunil** [model-checking/kani#2036]
When trying to get kani to work one often has to do small changes to a file. Kani recompiles all crates all over again even when only one file changed. Including proc macros, so if there's some technical reason why the code can't be reused for conversion to CBMC at least proc macros should be reusable.

**Comment by zhassan-aws** [comment]
Hi @Kixunil. This is indeed very annoying. We've had to disable incremental compilation because of a few bugs that we're working on fixing. This is tracked in #1736.
