### ISSUE TITLE
Kani doesn't work well with bolero tests

### ISSUE THREAD

**Issue by Kixunil** [model-checking/kani#2037]
There are two unrelated problems that compound into horrible experience: kani doesn't set `test` cfg and it ignores functions marked `#[test]`. The current workaround is a shitload of boilerplate.

I tried this code:

```rust
#[cfg(test)]
mod tests {
    #[cfg_attr(kani, kani::proof)]
    #[test]
    fn do_some_test() {
        // the body doesn't really matter
    }
}
```

using the following command line invocation:

```
cargo kani
```

with Kani version: 0.17.0

I expected to see this happen: kani runs prover for `do_some_test`

Instead, this happened: the test wasn't found, ended with this error:

> No proof harnesses (functions with #[kani::proof]) were found to verify.

Notably, this workaround makes it possible to run the test:

```rust
#[cfg(any(test, kani))]
mod tests {
    #[cfg_attr(kani, kani::proof)]
    #[cfg_attr(not(kani), test)]
    fn do_some_test() {
        // the body doesn't really matter
    }
}
```

which is not only annoyingly large but forces rewrite of attributes on all existing test support items (e.g. helper macros).

**Comment by zhassan-aws** [comment]
Hi @Kixunil. Thanks for the bug report. There is a `--tests` option to `cargo kani` that makes it set the `test` cfg.

**Comment by Kixunil** [comment]
That does seem to work but curiously it doesn't enable `dev-dependnecies` :(
