### ISSUE TITLE
 Update rust toolchain version for Kani 0.19

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#2044]
Biweekly update for the rust toolchain version. For Kani 0.19, we will target the new year version: nightly-2023-01-01 :)

**Comment by celinval** [comment]
This is currently blocked by https://github.com/diffblue/cbmc/issues/7462

**Comment by tautschnig** [comment]
https://github.com/diffblue/cbmc/issues/7462 is now resolved.

**Comment by zhassan-aws** [comment]
We skipped updating the rust toolchain for Kani 0.19. Updating it for Kani 0.20 is tracked in #2113. Closing this one.
