### ISSUE TITLE
RFC: Integration with `#[should_panic]`

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#2055]
Rust unit testing provides a `#[should_panic]` annotation for indicating tests that are expected to panic. This annotation also includes an optional argument to specify the text of the panic.

It'd be great if Kani used these annotations to determine the expected result for a harness.

**Comment by celinval** [comment]
Is this related to the second task of this issue? https://github.com/model-checking/kani/issues/600

**Comment by adpaco-aws** [comment]
Yes, it's indeed related.

What is not clear to me at this moment is what's best to propose:
 1. Integration with `#[should_panic]`: This is what unit tests use, but is specific to panics in Rust - Kani presents many more options for failure.
 2. Support for `#[expect_failure]`: This would be a new annotation that allows us to indicate Kani failures. The downside is that it wouldn't make use of existing `#[should_panic]` annotations, although there could be a way to work with them.

**Comment by adpaco-aws** [comment]
After some discussions with users, it's now clearer to me that what they want is the second option.

Hence, I'm closing this issue in favor of #600 (and assigned it to me).
