### ISSUE TITLE
Kani regression test expected/dynamic-error-trait/main.rs fails with latest CBMC

### ISSUE THREAD

**Issue by tautschnig** [model-checking/kani#2106]
**Proposed change:**
Using diffblue/cbmc@6a7b97cc89 (which is current develop, and between the already released 5.74.0 and the upcoming 5.74.0) results in a regression test failure that I believe is due to a limitation in Kani. Running the regression tests I get:
```
[...]

------------------------------------------
stderr:
------------------------------------------
warning: unused imports: `Read`, `Write`
 --> /home/ub-backup/tautschn/kani.git/tests/expected/dynamic-error-trait/main.rs:6:21
  |
6 | use std::io::{self, Read, Write};
  |                     ^^^^  ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: field `addr` is never read
  --> /home/ub-backup/tautschn/kani.git/tests/expected/dynamic-error-trait/main.rs:11:5
   |
10 | pub struct MemoryMapping {
   |            ------------- field in this struct
11 |     addr: *mut u8,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: Found the following unsupported constructs:
             - caller_location (1)

         Verification will fail if one or more of these constructs is reachable.
         See https://model-checking.github.io/kani/rust-feature-support.html for more details.

warning: 3 warnings emitted

thread '<unnamed>' panicked at 'Found property counter that doesn't match number format', kani-driver/src/cbmc_output_parser.rs:172:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------------------------------------



failures:
    [expected] expected/dynamic-error-trait/main.rs

test result: FAILED. 159 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 15.16s

Some tests failed in compiletest suite=expected mode=expected host=(none) target=(none)
```
Looking at the CBMC output, and comparing it to an earlier version, the only difference is:
* New: `[_ZN4core3ptr42drop_in_place$LT$std..io..error..Error$GT$17hd75fb0a3517a80c2E.recursion] recursion unwinding assertion: SUCCESS`
* Before: `[.recursion] recursion unwinding assertion: SUCCESS`

The latter seems bogus, and the new output produced by CBMC strictly seems to be an improvement. Either the output parser needs fixing, or we need to check why this mangled function name is seen in the output in the first place, which then perhaps returns the output to something that _is_ compatible with Kani's expected property format.

**Motivation:**
diffblue/cbmc@5c4503f2ef2fd altered the way we compute some property names. CBMC reserves the discretion to change property names, as long as they remain unique. On this occasion, however, it seems the previous property name was bogus, and Kani just seemed to apply a workaround.

**Comment by adpaco-aws** [comment]
The "before" case was handled by a special case in the output post-processor (see code below). It's nice that the change didn't go unnoticed. Any reason for "recursion" properties to not have a counter?

https://github.com/model-checking/kani/blob/81a8f8f6a4b22592a884b1d8fc78ac13d968a156/kani-driver/src/cbmc_output_parser.rs#L133-L135

**Comment by tautschnig** [comment]
> Any reason for "recursion" properties to not have a counter?

We do not currently distinguish the call stacks of recursive calls, so there cannot be multiple instances, just one per function name.
