### ISSUE TITLE
Multiple `--harness` arguments.

### ISSUE THREAD

**Issue by YoshikiTakashima** [model-checking/kani#2118]
It would be useful to have multiple `--harness` arguments.

For example, you may want to run `--harness a --harness b` and not run `c` because it is not yet implemented.
```rust
#[kani::proof]
fn a() {}
#[kani::proof] 
fn b() {}
#[kani::proof] 
fn c() {std::unimplemented!();}
```

This would also make it cleaner in Kani GitHub action where you don't need to run the action N times for each harness specified to be run.

**Comment by zhassan-aws** [comment]
Duplicate of #1778.

**Comment by YoshikiTakashima** [comment]
Thanks @zhassan-aws. Closing thus.
