### ISSUE TITLE
Some concrete playback regressions fail with latest CBMC

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#2123]
See https://github.com/model-checking/kani/actions/runs/3914097954/jobs/6690771575 for more details.

The failures are caused by a missing suffix for integer literals extracted for CBMC traces.
Expected:
```
        // -9223372036854775808l
```
Actual:
```
        // -9223372036854775808
```
This can be reproduced on the following program:
```rust
#[kani::proof]
fn main() {
    let x: u32 = kani::any();
    assert!(x != 0);
}
```
If I run it as follows with CBMC 5.72.0, I get:
```bash
$ kani simp_int.rs --no-assertion-reach-checks  --output-format old --enable-unstable --cbmc-args --json-ui | grep data
              "data": "0u",
              "data": "0u",
              "data": "0u",
              "data": "0u",
              "data": "0u",
              "data": "0u",
              "data": "0u",
              "data": "0u",
              "data": "FALSE",
              "data": "TRUE",
              "data": "FALSE",
              "data": false,
```
whereas if I run it with CBMC 5.73.0 or 5.74.0, I get:
```bash
$ kani simp_int.rs --no-assertion-reach-checks  --output-format old --enable-unstable --cbmc-args --json-ui | grep data
              "data": "0",
              "data": "0",
              "data": "0",
              "data": "0",
              "data": "0",
              "data": "0",
              "data": "0",
              "data": "0",
              "data": "FALSE",
              "data": "TRUE",
              "data": "FALSE",
              "data": false,
```

**Comment by zhassan-aws** [comment]
The following CBMC commit caused the difference:

https://github.com/diffblue/cbmc/commit/5f7e0ded56e28051f2d5a591caf16fe2261d2f5b#diff-03705c5153ed9df6a2fe9d5cf3a5dbfe38ec0014b8e19d45f574a1ddd22ab39b

**Comment by tautschnig** [comment]
While the commit is the one altering the behaviour, it's really a consequence of us merging `irep`s that are equal (under the notation of equality applicable to `irept`). So we will end up merging two `irept` for 32-bit unsigned bitvector types where only one of them carries the "#c_type" annotation. In GOTO, both of them are equivalent, it's just the output that's affected. Can I ask that playback adds a capability to add suffixes as needed?

**Comment by zhassan-aws** [comment]
Thanks for the analysis @tautschnig. I opened #2125 to update the expected files for those tests.
