### ISSUE TITLE
Remove `--function` option

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#2129]
**Proposed change:** We should include information about the public functions as part of the KaniMetadata when the reachability mode is `pub_fns`. We should stop merging all the metadata and goto binaries together.

**Motivation:** We have a special handling for `--function` today inside `kani-driver` because we cannot tell which artifacts are relevant to some function. So we just merge everything. If we treat functions as potential harnesses, we can get rid of the hack described above. We should also restrict the metadata to include functions that don't take any parameter.

**Comment by tedinski** [comment]
We could also just search the symtab files directly, it might be simpler that way.

**Comment by celinval** [comment]
Do we mean parse the symtab file or invoke some goto utility to print the functions available?

**Comment by celinval** [comment]
I am leaning towards adding information to the Metadata because is more reliable and it will work well even with mangled names. Since this will only be done for the target crate, the cost shouldn't be too high.

**Comment by celinval** [comment]
We no longer have a use for this flag. We used to keep it for the book runner, but we no longer use that. Users should use harnesses instead.
