### ISSUE TITLE
Add support to `simd_bitmask` intrinsic

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#2131]
Requested feature: Add support to `simd_bitmask` intrinsic
Use case: This intrinsic is commonly found during the code generation of the top 100 crates. Harnesses that exercise this intrinsic will fail due to unimplemented feature.
Link to relevant documentation (Rust reference, Nomicon, RFC):

**Comment by celinval** [comment]
Here is the definition from the intrinsics documentation:

https://github.com/rust-lang/rust/blob/338cfd3cce448f576dbac48438018fc65cef8982/library/portable-simd/crates/core_simd/src/intrinsics.rs#L134-L144

From the actual Masks specification, the integer to mask operation is [documented as](https://doc.rust-lang.org/core/simd/struct.Mask.html#method.from_int_unchecked):

> Converts a vector of integers to a mask, where 0 represents false and -1 represents true.
> [Safety](https://doc.rust-lang.org/core/simd/struct.Mask.html#safety)
>
> All lanes must be either 0 or -1.

**Comment by tautschnig** [comment]
Given this specification I believe that Kani should generate a "concatenation" expression where each operand will be an "if" with a condition of "lane notequal 0" and "1" and "0" as the two cases. (I still don't understand under which condition an array is to be produced as result.)

**Comment by celinval** [comment]
The array will be produced if the input vector has more than 128 lanes. You basically need one bit per lane.

**Comment by celinval** [comment]
Kani can do this, but it will be more efficient since CBMC can probably encode operations that result in a single bit, while Kani will have to generate the results for each lane first, then join them in different bytes.

**Comment by celinval** [comment]
This intrinsic seems to be used by string comparison and hash map / hash set functions such as insert.

**Comment by celinval** [comment]
After talking to @remi-delmas-3000, we decided to implement this on the Kani side since CBMC modeling happens before bitblasting. So we would still need to do this operation byte-wise.

**Comment by celinval** [comment]
I created a basic Rust implementation of simd_bitmask that we could potentially use as a stub for this. However, I bumped into an issue while trying to transmute a SIMD structure. I created https://github.com/rust-lang/rust/issues/113465 to capture the issue.

It's not clear if this issue will affect the verification use flow since we will hook the implementation inside the `kani-compiler`. However, it would be really nice to be able to add tests to the library implementation itself.

**Comment by celinval** [comment]
This work is also blocked by https://github.com/model-checking/kani/issues/2590

**Comment by workingjubilee** [comment]
You can't just use tuple access. You instead have to replicate our insane pattern for a legal read of a Simd type, sorry:

```rust
    /// Converts a SIMD vector to an array.
    #[inline]
    pub const fn to_array(self) -> [T; N] {
        let mut tmp = core::mem::MaybeUninit::uninit();
        // SAFETY: writing to `tmp` is safe and initializes it.
        //
        // FIXME: We currently use a pointer store instead of `transmute_copy` because `repr(simd)`
        // results in padding for non-power-of-2 vectors (so vectors are larger than arrays).
        //
        // NOTE: This deliberately doesn't just use `self.0`, see the comment
        // on the struct definition for details.
        unsafe {
            self.store(tmp.as_mut_ptr());
            tmp.assume_init()
        }
    }
```

**Comment by celinval** [comment]
Thanks @workingjubilee ! I think https://github.com/rust-lang/portable-simd/pull/339 also has another workaround that seems to work:

https://github.com/rust-lang/portable-simd/blob/7c7dbe0c505ccbc02ff30c1e37381ab1d47bf46f/crates/core_simd/src/vector.rs#L162-L170

```rust
    pub const fn as_array(&self) -> &[T; N] {
        // SAFETY: `Simd<T, N>` is just an overaligned `[T; N]` with
        // potential padding at the end, so pointer casting to a
        // `&[T; N]` is safe.
        //
        // NOTE: This deliberately doesn't just use `&self.0`, see the comment
        // on the struct definition for details.
        unsafe { &*(self as *const Self as *const [T; N]) }
    }
```
