### ISSUE TITLE
Migrate loop contracts to dynamic frames in CBMC

### ISSUE THREAD

**Issue by remi-delmas-3000** [model-checking/kani#2155]
**Proposed change:**
Migrate loop contract transformation from `src/goto-instrument/contracts/contracts.cpp` to ``src/goto-instrument/contracts/dynamic-frames/dfcc.cpp`

**Motivation:**
Extend the new contract contract system complete by including loop contracts.

**Comment by qinheping** [comment]
Related PRs: [PR#7127](https://github.com/diffblue/cbmc/pull/7127), [PR#7300](https://github.com/diffblue/cbmc/pull/7300)

We may also want to add dependency checks for loop-assigns clauses.

**Comment by qinheping** [comment]
DFCC for loop contracts is implemented in [PR#7541](https://github.com/diffblue/cbmc/pull/7541).
