### ISSUE TITLE
Assess scan should include failures to build a package

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#2165]
Requested feature: When running `cargo kani assess scan` users should have visibility to the packages that Kani failed to assess. 
Use case: We should provide more visibility to the user why `assess` failed to analyze some crates.
Link to relevant documentation (Rust reference, Nomicon, RFC):

Test case: Run the assess script to analyze the top 100 failures. The results will have the following info:

```rust
Assessed 82 successfully, with 18 failures. 
```

However, there is no visibility to why those failures occurred. Manually inspecting some of the logs, it looks like there are a diverse set of failures that include some `kani-compiler` crashes, some ambiguous package selection issues while invoking Cargo...

**Comment by celinval** [comment]
This is related to #2058 but it is the work related to the `scan` part of it.

**Comment by tedinski** [comment]
Also related to #2053: scan has an easy path to doing this, but regular assess did not. Switching behaviors so that regular assess is always single-package only is probably the best path forward.
