### ISSUE TITLE
Performance regression with new rust toolchain

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#2191]
Our recent efforts to upgrade the rust toolchain to `nightly-2023-01-23` https://github.com/model-checking/kani/pull/2149 is currently blocked due to a significant performance regression.

2 out of 3 tests added to measure the performance of Kani with Vectors seems to be highly affected. Here the analysis we added to the PR for `tests/perf/vec/box_dyn`.

Running the failing test in my local machine with `cargo kani`, I got the following:

| Configuration  | Time | Memory |
|--------------------|---------|------------|
| main  (CBMC 5.75)    | 5.74s | 165MB |
| this PR (CBMC 5.75) |  206s  | 16GB    |
| main  (CBMC 5.70)    | 200.s | 16GB |

Note that the time in this PR is very similar to the one I obtained when running `main` with an older CBMC version (before https://github.com/diffblue/cbmc/pull/7230).

I wonder if whatever has changed neutralized the optimization that @tautschnig introduced. 😕

_Originally posted by @celinval in https://github.com/model-checking/kani/issues/2149#issuecomment-1416558001_

**Comment by celinval** [comment]
@tautschnig do you think you can take a look at this? Thanks!

**Comment by tautschnig** [comment]
It seems that the way null-ness is tested has been changed, and now CBMC no longer manages to simplify this. The following C snippet demonstrates the same problem (which we'll have to make CBMC solve solely via constant propagation and simplification):
````C
union U
{
  void * ptr;
  __CPROVER_size_t n;
};

int main()
{
  int *p = __CPROVER_allocate(sizeof(int), 0);
  union U u = { .ptr = p };
  __CPROVER_assert(u.n != 0, "is not null");
}
````
Working on a fix.

**Comment by tautschnig** [comment]
Fixed in https://github.com/diffblue/cbmc/pull/7556.

**Comment by celinval** [comment]
Thank you so much!! @tautschnig
