### ISSUE TITLE
Reaching Out : Contributing to project kani

### ISSUE THREAD

**Issue by shubhamkumar13** [model-checking/kani#2222]
I apologise for posting this because this is not an issue and I wasn't sure how to reach out.

I was interested to work on the kani project but I wasn't aware of any channels to have a chat with.

One of the folks from SIGPLAN-M pointed me to this project when I expressed my interest for working on formal verification last week.

I was also informed that this project is still in development and not in use. Please do let me know how to contribute to this project.

Thanks!

**Comment by zhassan-aws** [comment]
Hi @shubhamkumar13. Thanks for reaching out and for expressing interest in contributing to the Kani project! I will message you to discuss the next steps.
