### ISSUE TITLE
Make `PhantomData` and `PhantomPinned` impl `kani::Arbitrary`

### ISSUE THREAD

**Issue by cameron1024** [model-checking/kani#2224]
**Proposed change:**

Implement `kani::Arbitrary` for `PhantomData<T>` (blanket impl for all `T`) and `PhantomPinned`

**Motivation:**

I have a struct which represents "bytes that can be deserialized to a  `T`":
```rust
struct TypedBytes<'a, T> {
  bytes: &'a [u8],
  _marker: core::marker::PhantomData<T>,
}
```
I'd like to be able to use `#[cfg_attr(kani, derive(kani::Arbitrary))]` on this struct, but currently I can't since `PhantomData` doesn't implement `Arbitrary`.

Since they are ZSTs, there are no values of either type, so presumably don't interact with symbolic values? I can't see a harm in allowing this, but I'm not familiar with kani, so let me know if I'm not understanding something :grin: 

Thanks

**Comment by zhassan-aws** [comment]
Hi @cameron1024. Thanks for submitting the feature request! I think this makes a lot of sense. We will look into it.
