### ISSUE TITLE
Create script to update CBMC-version upon manual trigger

### ISSUE THREAD

**Issue by karkhaz** [model-checking/kani#2243]
Create a cronjob that posts a pull request to Kani, that bumps the version of CBMC and CBMC Viewer to the latest version in `kani-dependencies`.

The cronjob should then send an email to oncall with a link to the PR. Oncall should simply have to approve and merge the PR.

Unit tests for that PR should be sufficient to discover potential issues with upgrading CBMC versions.

**Comment by jaisnan** [comment]
want to note that there will be times where we don't want to update cmbc necessarily in a release, so this should not be a cronjob but rather a script that runs on a manual trigger.
