### ISSUE TITLE
Kani doesn't have an `--exact` flag to call for singular harnesses

### ISSUE THREAD

**Issue by jaisnan** [model-checking/kani#2285]
Requested feature:

Like rust tests, `kani` needs an `--exact` flag that matches against a harness instead of the substring match that happens by default. substring match needs to be the default method, but users should be able to specify harnesses.

**Comment by celinval** [comment]
@jaisnan I just wanted to double check if it's OK if we model it the same way as rust tests model `--exact`? I.e., it requires the fully qualified name for the test function to match the given name.

**Comment by jaisnan** [comment]
I have a PR out for the changes to use the fully qualified name, and so far it seems to be working fine. 
I'm assuming it won't be necessitated and that the fuzzing search for harnesses that we do have, will work just the same. If so, I say that we add the `--exact` flag the way you're suggesting, and that the extension should use it by default but it will also use the fuzzing approach as a backup if that fails. Does that make sense?

**Comment by celinval** [comment]
Yes. Once we have the list harness option, it will be easier to know for sure the qualified name too.

**Comment by jaisnan** [comment]
Makes sense to me to model it after cargo. Good for the long term as well.
