### ISSUE TITLE
Small documentation issue for `kani::any_where`

### ISSUE THREAD

**Issue by roypat** [model-checking/kani#2332]
Hey kani team, 
I noticed a small error in the rustdoc for the `kani::any_where` function that threw me off slightly when chasing down some rustc type inference weirdness.

I tried this code:
The documentation mentions the following example
```rust
let inputA = kani::any_where::<std::num::NonZeroU8>(|x| *x < 12);
fn_under_verification(inputA);
```

with Kani version: 0.24.0, latest from github

I expected to see this happen:
The example to be valid

Instead, this happened: 
The `kani::any_where` function has two type argument, so in the example above it should be invoked as `kani::any_where::<std::num::NonZeroU8, _>(...)`. 

However, since having to put the underscore into the turbofish is slightly ugly, I was wondering if maybe the signature of `kani::any_where` could instead be `fn kani_any<T: kani::Arbitrary>(f: impl FnOnce(&T) -> bool) -> T`? (this question is mainly why this is an issue instead of a PR)

**Comment by zhassan-aws** [comment]
Good catch @roypat! I'd prefer if we just fix the documentation to avoid making a breaking change to the API.
