### ISSUE TITLE
Failure to cast back to `&str` from `&[u8]`

### ISSUE THREAD

**Issue by avanhatt** [model-checking/kani#241]
#235 adds the test `src/test/cbmc/Strings/copy_empty_string_by_intrinsic_fixme.rs`, which has this chunk:

```rust 
        let dest_slice : &[u8] = from_raw_parts(dest, l);
        let dest_as_str : &str= str::from_utf8(dest_slice).unwrap();
        assert!(dest_as_str.len() == l);
```

With failures verification with:
```rust
[...copy_empty_string_by_intrinsic.assertion.2] line 1035 unreachable code: FAILURE
[...copy_empty_string_by_intrinsic.assertion.1] line 1037 a panicking function std::result::unwrap_failed is invoked: FAILURE
[...copy_string.assertion.2] line 28 assertion failed: dest_as_str.len() == l: FAILURE
```

**Comment by danielsn** [comment]
You might want to use https://doc.rust-lang.org/std/str/fn.from_utf8_unchecked.html
https://doc.rust-lang.org/std/str/fn.from_utf8.html - the conversion we are using is expected to fail if the bytes are not valid unicode.

**Comment by zhassan-aws** [comment]
@jaisnan Please check if this one is still reproducible.

**Comment by zhassan-aws** [comment]
This is still reproducible and is due to a missing std function. See this comment for how we plan on addressing this issue: https://github.com/model-checking/kani/issues/576#issuecomment-1095295801.
