### ISSUE TITLE
Cannot checkout this repo on windows because of `:` character in path

### ISSUE THREAD

**Issue by crlf0710** [model-checking/kani#2432]
git will report error with:
```text
error: invalid path 'tools/bookrunner/configs/books/Rust by Example/Custom Types/Enums/Testcase: linked-list/5.props'
```

**Comment by adpaco-aws** [comment]
Hi @crlf0710 , thanks for the issue! I'll see if we can rename the bookrunner examples somehow to avoid this error.

**Comment by adpaco-aws** [comment]
Resolving because #3123 removed all `.props` files.
