### ISSUE TITLE
Concrete playback not working for `Result<T, E>` when `T` is `()`

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#2453]
I tried this code:

```rust
#[cfg(kani)]
mod verify {
    #[kani::proof]
    fn any_is_ok() {
        let result: Result<(), bool> = kani::any();
        kani::cover!(result.is_ok());
    }
}

```

using the following command line invocation:

```
kani --enable-unstable --concrete-playback=inplace
```

then followed wiki to build and run the harness.

with Kani version: 0.27.0

I expected to see this happen: Harness succeed

Instead, this happened: Harness fails with error:
```
thread 'main' panicked at 'Not enough det vals found', /home/ubuntu/kani/library/kani/src/concrete_playback.rs:52:62

```

**Comment by YoshikiTakashima** [comment]
On my side, this issue seems fixed on caec631d112c15b10d83863b75820dd305c7bf9d. Is it same for you @celinval?

**Comment by celinval** [comment]
@YoshikiTakashima were you able to run the test? For me it still shows the same error. I think the problem is when we call `kani::any()` in a zero sized type. The following example has the same problem:
```rust
//! test.rs
#[kani::proof]
fn any_is_ok() {
    let unit: () = kani::any();
    kani::cover!(unit == ());
}
```
Running these commands:
```
kani --enable-unstable --concrete-playback=inplace test.rs
kani playback -Z concrete-playback test.rs
```

**Comment by YoshikiTakashima** [comment]
I replicated it. Was forgetting the second command.
