### ISSUE TITLE
Concrete Playback playback subcommand picks up regular unit tests and fails to compile

### ISSUE THREAD

**Issue by jaisnan** [model-checking/kani#2489]
When there are other unit tests present, running `cargo kani playback -- kani_concrete_playback_harness_i64_13477596495325479973` for example, gives compilation errors that are picked up from unit tests unrelated to kani. The command breaks completely and displays an empty output.

**Comment by celinval** [comment]
After discussing offline, the problem seems to be with the integration tests, not with the playback back mode. The integration tests were using functions that were not defined when `kani` config was set. We can provide options for the user to disable the integration tests though.
