### ISSUE TITLE
Finish refactoring on how we handle the metadata file for Tests and PubFns

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#2493]
**Proposed change:** To solve #1841 we moved the metadata generation to the `kani_compiler` for the Harness reachability mode. We should also change how we handle Tests and PubFns.

**Motivation:** The code has two very distinct logic to handle metadata, which is more fragile and harder to maintain. We only partitioned this work into separate issues to reduce the size of the PR.

Note: We also need to ensure we store unsupported features to the metadata files.

**Comment by celinval** [comment]
This is no longer needed since #3245.

**Comment by carolynzech** [comment]
Closing since this is no longer needed.
