### ISSUE TITLE
RFC: Output - Harness listing/enumeration

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#2573]
Requested feature: A section of our output dedicated to enumerating or listing harnesses found in a project, how many will run for verification, etc. This is likely a requirement for #2563 , which will be an attempt to represent multi-harness progress.
Use case: Multi-harness verification - Nowadays users don't get any feedback about which harnesses are run or in which order.
Link to relevant documentation (Rust reference, Nomicon, RFC): #2563

**Comment by celinval** [comment]
I think this is related to #1612. I think we should add a list option / subcommand. I would also suggest that we list all the contracts in Kani
