### ISSUE TITLE
Coverage option that does not require `cbmc-viewer`

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#2610]
Requested feature: In the past, Kani has relied on `cbmc-viewer` to generate coverage reports. This requires Kani to make additional calls to `cbmc` with the `--cover` flag, then `cbmc-viewer` to essentially perform postprocessing on that output. Unfortunately, the information reported by `cbmc-viewer` isn't tested thoroughly (see #2048). But actually, Kani already has the tools required for generating coverage-oriented information. Having an option that enables this would allow us to remove the `cbmc-viewer` dependency and have end-to-end testing for coverage information.

Use case: Coverage reports.
Link to relevant documentation (Rust reference, Nomicon, RFC): N/A

**Comment by jaisnan** [comment]
Should we tag our PR for this issue?
