### ISSUE TITLE
How does kani ensure memory safety?

### ISSUE THREAD

**Issue by kiyoakii** [model-checking/kani#2629]
Hi there👋!

This is more like a learning and discussion post. I just found kani and think it's super useful in many ways. 

I am wondering how kani ensures memory safety with unsafe code. I have some basic knowledge of symbolic execution and it's always hard for symbolic execution engines to make assumptions on memory addresses. And my understanding of model checkers is very limited. It seems the very first difference is that I need to write the conditions for using kani.

My questions are: 
1. Does kani require a memory model and what assumptions does it make for memory addresses? For example, how does kani know it's wrong to write ``unsafe { return *(4096 as *const u32) };``
2. How can I construct a check to ensure that if a Rust program passes kani's check, it is SFI-safe (Software-Fault-Isolation-safe), meaning it will not access any unauthorized memory? Is this even possible?
3. Does kani leverage Rust's stricter rules, such as ownership and lifetime systems, within its implementation for improved symbolic verification performance or ease of use compared to C/C++?

I would greatly appreciate any response and discussion on these topics! Thanks!!

**Comment by zhassan-aws** [comment]
Hi @kiyoakii. Thanks for your questions! Kani relies on CBMC's pointer checks to ensure memory safety. The following links describe how memory is modeled in CBMC and the checks that are instrumented:

https://github.com/diffblue/cbmc/blob/develop/doc/cprover-manual/modeling-pointers.md
https://diffblue.github.io/cbmc/cprover-manual/md_memory_primitives.html
https://diffblue.github.io/cbmc/memory-bounds-checking.html

You can also refer to the CBMC manual for a brief introduction of bounded model checking and how it works on C programs:

https://diffblue.github.io/cbmc/background-concepts.html#BMC_section

And here are the answers to your other questions:
1. Kani does not require the user to provide a memory model. It relies on CBMC's memory model which makes some assumptions and has some limitations (e.g. https://github.com/diffblue/cbmc/issues/2117).
2. Kani does not capture all undefined behavior in a program (see [this section of the documentation](https://model-checking.github.io/kani/undefined-behaviour.html) for the limitations). But assuming the program does not contain any undefined behavior, if all checks pass, then the memory accesses in the program as defined by the harness are legal.
3. In some cases, Kani provides "hints" to CBMC that improve verification performance (e.g. see Kani's `--restrict-vtable` option). But currently, it does not leverage ownership or lifetimes for that purpose.

**Comment by kiyoakii** [comment]
Thank you so much for the explanation and links as they are really helpful. I have a follow-up to question 2: I learned that there doesn't exist an exhaustive list of UBs. So I'm trying to get a sense of what's the best conclusion we can get. 

For example, the limitation section states:

> - Breaking the pointer aliasing rules (http://llvm.org/docs/LangRef.html#pointer-aliasing-rules).
Kani can detect if misuse of pointers causes memory safety or assertion violations, but does not track reference lifetimes.
> - Mutating immutable data.
Kani can detect if modification of immutable data causes memory safety or assertion violations, but does not track reference lifetimes.

What does "not tracking reference lifetimes" mean? Is there any case this limitation makes it impossible to detect some memory unsafety, or is it just about efficiency and detection logic like we discussed in question 3?

If the latter is true, then can we say Kani can fully ensure the memory safety of a single-thread Rust code that doesn't use FFI calling, compiler intrinsic, platform-specific features, or inline assembly?

**Comment by zhassan-aws** [comment]
> Could you please explain more about the meaning of "not tracking reference lifetimes" in this context?

See for example the program in this [SO thread](https://stackoverflow.com/a/54242058/7752529). This program has undefined behavior that [MIRI ](https://github.com/rust-lang/miri) detects through checking stacked borrows, but Kani doesn't because it doesn't track references and mutability.

> Is there any case this limitation makes it impossible to detect some memory unsafety, or is it just about efficiency and detection logic like we discussed in question 3?

If a program contains any type of undefined behavior that Kani does not check (e.g. the program mutates an immutable variable in an unsafe block), the Rust compiler may handle the program in unexpected ways, which, in turn, may lead to memory unsafety. Kani may fail to detect the memory unsafety in those cases. Quoting the explanation in [the undefined behavior section of the Kani documentation](https://model-checking.github.io/kani/undefined-behaviour.html#the-effect-of-undefined-behaviour-on-program-verification):

> If a program has UB, the semantics of the rest of the program are undefined. As a result, if the program under verification contains UB then, in principle, the program (including its representation in MIR analyzed by Kani) has no semantics and hence could do anything, including violating the guarantees checked by Kani. This means that verification results are subject to the proviso that the program under verification does not contain UB.

For your last question:

> If the latter is true, then can we say Kani can fully ensure the memory safety of a single-thread Rust code that doesn't use FFI calling, compiler intrinsic, platform-specific features, or inline assembly?

I think this kind of program is too restricted, and may not even be possible? The standard library uses a lot of unsafe code and intrinsics, and these are considered part of the program. What I think is safe to say is that Kani ensures memory safety if a program does not contain any behavior that is considered undefined by the Rust compiler and LLVM. Of course, this is assuming the absence of bugs in Kani itself, its backend engine (CBMC), and the SAT solver it uses.

**Comment by kiyoakii** [comment]
Thanks for the clear explanation! So, with the assumption that a program doesn't contain UB, Kani ensures memory safety. Then the problem we are facing is more about 1) the absence of a comprehensive list of UBs and 2) the lack of a method to detect all instances of UB?

> I think this kind of program is too restricted, and may not even be possible? The standard library uses a lot of unsafe code and intrinsics, and these are considered part of the program.

I agree! At the same time, do we have more confidence in Rust's standard library? I've seen works like Ralf's RustBelt, which involves manually transcribing Rust code into λ-Rust code and then using a theorem prover to verify it. Do you know if anyone is verifying the up-to-date standard library in this manner, if possible?

**Comment by zhassan-aws** [comment]
> Then the problem we are facing is more about 1) the absence of a comprehensive list of UBs and 2) the lack of a method to detect all instances of UB?

Correct.

> At the same time, do we have more confidence in Rust's standard library?

There have been bugs found in the standard library before (e.g. https://model-checking.github.io/kani-verifier-blog/2022/06/01/using-the-kani-rust-verifier-on-a-rust-standard-library-cve.html). 

> Do you know if anyone is verifying the up-to-date standard library in this manner, if possible?

Not that I'm aware of.

**Comment by zhassan-aws** [comment]
Closing this issue. Feel free to reopen or create a new issue if you have further questions.
