### ISSUE TITLE
Concrete playback fails when temp folder is on a different mount point

### ISSUE THREAD

**Issue by yvizel** [model-checking/kani#2705]
Hi,

I built Kani on Ubuntu 22.04 and I am getting the following output when running the regression.

[regression_output.txt](https://github.com/model-checking/kani/files/12420130/regression_output.txt)

What can it be?

**Comment by tautschnig** [comment]
Would you mind doing `export RUST_BACKTRACE=1` and re-run those tests? All errors are of the form
```
thread '<unnamed>' panicked at kani-driver/src/util.rs:64:18:
called `Result::unwrap()` on an `Err` value: Error renaming file /tmp/kani_tmp_2761667929_concrete_playback.tmp

Caused by:
    Invalid cross-device link (os error 18)
```
but it would be helpful to know where we are invoking `rename` from.

**Comment by yvizel** [comment]
Attached is the new log.
[regression.txt](https://github.com/model-checking/kani/files/12422300/regression.txt)

**Comment by celinval** [comment]
This could be a bug in Kani. Is your `/tmp` folder mounted in a different partition as our home folder?

We currently invoke [`std::fs::rename()`](https://doc.rust-lang.org/std/fs/fn.rename.html) to override the new file, but the documentation of this function clearly states that "This will not work if the new name is on a different mount point."

**Comment by yvizel** [comment]
@celinval - yes. The home folder is nfs while tmp is local to the machine.
