### ISSUE TITLE
CBMC failed with status 137

### ISSUE THREAD

**Issue by weaversa** [model-checking/kani#2715]
With Kani version 0.35.0 some of our previously working proofs are now failing with the message `CBMC failed with status 137`.

I don't have the ability right now to provide the rust code.

**Comment by weaversa** [comment]
At the very least, it would be nice to know what this status code means. Thank you!

**Comment by zhassan-aws** [comment]
This means that the process ran out of memory. Do you know the peak memory usage of those proofs with the previous version of Kani?

**Comment by weaversa** [comment]
Thank you!
