### ISSUE TITLE
design by contract

### ISSUE THREAD

**Issue by drdozer** [model-checking/kani#2721]
# Requested feature: design by contract

The ability to annotate declarations and blocks with contracts specifying constraints on their behaviour, and have these become properties to be proven.

In design by contract, the functions, types and blocks are annotated with invariants, variants, post-conditions and pre-conditions. These collectively define an upper bound on allowed behaviour.

One benefit of this style is that it keeps the contract and potentially the proof strategy for that contract by the code it applies to. It becomes part of the documentation (documentation by contract) and encourages a specification-driven design. It is complementary to having a separate proof suite, as currently supported.

For example, see:

* https://github.com/xldenis/creusot
* https://gitlab.com/karroffel/contracts

**Comment by jaisnan** [comment]
Thank you for the suggestion @drdozer ! We agree with your request to allow users to define behavior through contracts. On a related note, we have begun work to allow users to define function contracts. You can view the RFC for that [here](https://model-checking.github.io/kani/rfc/rfcs/0009-function-contracts.html) and view the tracking milestone for that [here](https://github.com/model-checking/kani/milestone/31).
