### ISSUE TITLE
`perf-benchcomp` CI fails when pushing a new release

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#2744]
**Proposed change:** Do not run the `perf-benchcomp` when pushing a release tag.

**Motivation:** `perf-benchcomp` jobs get triggered after pushing a release tag and they fail with some error that I don't understand. It doesn't make sense to run `perf-benchcomp` in CI anyway because the candidate commit will have already done it.

I was surprised to find that the CI job failed when doing the 0.36.0 release (job [here](https://github.com/model-checking/kani/actions/runs/6110889802/job/16585358347)). Then I check what happened during the 0.35.0 release and saw the same here (job [here](https://github.com/model-checking/kani/actions/runs/5957239259/job/16159564100)).

**Comment by tautschnig** [comment]
The root cause of the problem is that `github.event.before` isn't set for new branches, and likely the same is true for tags. The fix should likely be that we remove 
```
    tags:
      - kani-*
```
from `.github/workflows/bench.yml`. We still have the performance comparison on the merge into `main` anyway.
