### ISSUE TITLE
Values left over after playback.

### ISSUE THREAD

**Issue by jswrenn** [model-checking/kani#2761]
Running this:
```
git clone -b kani-bug https://github.com/google/zerocopy
cd zerocopy
cargo kani -Z concrete-playback --concrete-playback=inplace
cargo kani playback --package zerocopy -Z concrete-playback
```
...results in this playback failure:
```
---- byteorder::tests::kani_concrete_playback_test_native_endian_11400111218853981883 stdout ----
thread 'byteorder::tests::kani_concrete_playback_test_native_endian_11400111218853981883' panicked at /__w/kani/kani/library/kani/src/concrete_playback.rs:32:9:
At the end of concrete playback, there were still these concrete values left over `[[128, 128, 155, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128], [255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255], [255, 255, 255, 255], [255, 255], [255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [80, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 253, 255], [255, 255, 255, 255, 255, 255, 255, 255], [247, 128, 128, 128, 128, 128, 255, 128], [255, 255, 255, 255], [0, 255, 255, 127], [255, 255], [255, 255]]`. This either happened because: 1) Your code/harness changed after you generated this concrete playback unit test. 2) There's a bug in Kani. Please report the issue here: <https://github.com/model-checking/kani/issues/new?assignees=&labels=bug&template=bug_report.md>
```
when using cargo-kani v0.36.0.

**Comment by feliperodri** [comment]
Thank you for reporting this @jswrenn! I was able to reproduce the error. Indeed, this might be a bug in Kani concrete playback feature. At a first glance, I couldn't see any problems with the harnesses that mentioned in the error messages (i.e., `byteorder::test_native_endian` and `lib::test_validate_cast_and_convert_metadata`). Let's investigate where the left over values are coming from first.

**Comment by jswrenn** [comment]
I discovered this morning that the harness *should* have a verification issue, due to a difference in behavior between `kani::any()` and sampling values with the `rand` crate:
- the range of `kani::any()` includes `NaN`
- the range of `Rng::sample` excludes `NaN`. 

I confirmed this by extracting out the `byteorder` module into a separate crate and then minimizing it until just the problematic harness remained. With the final, minimized form, the concrete playback crash didn't materialize and I was able to discover the `NaN` issue. Unfortunately, I don't know at what stage of this process the concrete playback crash issue disappeared.

**Comment by jaisnan** [comment]
Thanks for the issue @jswrenn and it's great to hear that you were able to discover the `Nan` issue by minimizing the module. 

We think the confusion could be coming from the fact that `concrete_playback` tests are invoked with the other tests, i.e with`cfg(test)` which uses `rand` underneath while the harness itself uses the non-det variable `kani::any()`. The difference in the expected environment could be causing the issue.

We tried changing [`cfg(test)` at line 501 in byteorder.rs](https://github.com/google/zerocopy/blob/76d0f6ba4f79c813c30c1eef2476a0b5a2cb0d33/src/byteorder.rs#L501C12-L501C12) to `cfg(not(kani))` to resolve the environment and got the expected assertion error

```
test byteorder::tests::kani_concrete_playback_test_native_endian_4629248616999694986 ... FAILED

failures:

---- byteorder::tests::kani_concrete_playback_test_native_endian_4629248616999694986 stdout ----
thread 'byteorder::tests::kani_concrete_playback_test_native_endian_4629248616999694986' panicked at library/kani/src/lib.rs:98:5:
assertion failed: from_native.get() == updated
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The error from `concrete_playback` wasn't intuitive and the documentation is lacking in this area, so the issue was helpful in pointing this out.

**Comment by celinval** [comment]
> We tried changing [`cfg(test)` at line 501 in byteorder.rs](https://github.com/google/zerocopy/blob/76d0f6ba4f79c813c30c1eef2476a0b5a2cb0d33/src/byteorder.rs#L501C12-L501C12) to `cfg(not(kani))` to resolve the environment and got the expected assertion error

Hi @jswrenn, were you able to check if the change proposed by @jaisnan fixes the problem? Thanks

**Comment by jaisnan** [comment]
As discussed offline with @jswrenn, we shall improve documentation and the error messaging but the workaround works.

The issue tracking the user improvement is here - 
https://github.com/model-checking/kani/issues/2786
