### ISSUE TITLE
Problem with `NoBackIter<T>::next` in  `noback_vec`

### ISSUE THREAD

**Issue by caballa** [model-checking/kani#2766]
I think that the mock for `next` defined in `noback_vec` class might be unsound (https://github.com/model-checking/kani/blob/main/library/kani/stubs/Rust/vec/noback_vec.rs#L190)

`self.start` must be incremented by one before the functions returns. Something like:

```
fn next(&mut self) -> Option<T> {
        let res = if self.start == self.end { None } else { Some(__nondet::<T>())};
        self.start = self.start + 1;
        return res
    }
```

A common situation where the current mock implementation might produce unsound results:

1. `let iter = NoBackIter::new(len)` where `len > 0` 
2. Any call to `iter.next()` will NEVER returns `None` since `self.start  < self.end`

**Comment by zhassan-aws** [comment]
Thanks for filing this issue @caballa! You are correct: the function is missing an increment operation.

The stubs library is actually obsolete, and is not currently used anywhere in Kani. I'll open a PR to delete it since it's not tested, and may contain bugs.
