### ISSUE TITLE
Fix casting warnings in `Projection::new`

### ISSUE THREAD

**Issue by avanhatt** [model-checking/kani#277]
There is a commented-out assertion with a TODO in `Projection::new`: the assertion fails on some regression tests; but also on some standard library issues that would be useful to have an actual check for. Once we fix the regressions we should enable it.

```rust
        // TODO: these assertions fail on a few regressions. Figure out why.
        // I think it may have to do with boxed fat pointers.
        // assert!(
        //     Self::check_expr_typ(&goto_expr, &mir_typ_or_variant, ctx),
        //     "\n{:?}\n{:?}",
        //     &goto_expr,
        //     &mir_typ_or_variant
        // );
```

**Comment by avanhatt** [comment]
Example: boxed closures, like this:

```rust
   // Create a boxed once-callable closure
    let f: Box<dyn FnOnce()> = Box::new(|| {});
    f();
```

**Comment by tautschnig** [comment]
Not that I have a solution here as to why "Pointer" and "FlexibleArray" seem to be confused here, but I just wanted to note that CBMC now takes a `#flexible_array_member` annotation on flexible array members.

**Comment by celinval** [comment]
From what I gather so far, it looks like we are incorrectly using Struct { Pointer } when adding the symbol to the symbol table. Trying to pin down where this is happening.

**Comment by celinval** [comment]
Oh, I think I found it. :)

https://github.com/model-checking/kani/blob/e6fb98834a72a30c80875da9d42de0e790fcdcd7/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs#L770

It looks like we are assuming in a lot of places in this file that a slice is encoded as:
```rust
struct<T> Slice{
   data: const* T,
   len: usize,
}
 ```
But in the following line we expect a FlexibleArray:
https://github.com/model-checking/kani/blob/e6fb98834a72a30c80875da9d42de0e790fcdcd7/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs#L542
