### ISSUE TITLE
Installing Kani on ARM64 Linux

### ISSUE THREAD

**Issue by rhakobyan** [model-checking/kani#2805]
Requested feature: Ability to install Kani on ARM64 Linux machines
Use case: Currently, installing Kani through `cargo install --locked kani-verifier` on ARM64 Linux machines fails because Kani binaries are not distributed for the `aarch64-unknown-linux-gnu` target. The workaround is manually building Kani on ARM64 Linux. However, this approach is tedious and ideally it would be better to have the ability of installing Kani without needing to build it manually.

Otherwise, having the ability to analyse ARM64 codebase with Kani installed on x86 machines would also be very beneficial.

**Comment by adpaco-aws** [comment]
Hi @rhakobyan , thanks for opening the feature request!

> Otherwise, having the ability to analyse ARM64 codebase with Kani installed on x86 machines would also be very beneficial.

#2402 tracks this.
