### ISSUE TITLE
Command to build proofs without running the verification process

### ISSUE THREAD

**Issue by arctic-alpaca** [model-checking/kani#2856]
**Requested feature:** A build command to build all harnesses without actually running the verification process.

**Use case**: Some proofs cannot be run in CI because the runner's resources are not sufficient. I'd still like to make sure no change can accidentally cause a proof to stop compiling. As far as I can tell, there is currently no way to do this and it is not covered by normal CI tests/compilation because of the `#[cfg(kani)]` attributes and kani not being used as a dev dependency.

**Comment by zhassan-aws** [comment]
Thanks for the feature request. The `--only-codegen` option should achieve the requested behavior.

**Comment by arctic-alpaca** [comment]
Thanks, that is exactly was I was looking for! Is this documented somewhere? The `--help` command does not seem to mention this.

**Comment by arctic-alpaca** [comment]
The `--help` command does indeed mention this, my bad, sorry. I only checked `-h`.
