### ISSUE TITLE
Setup crashes because CBMC-Viewer has a dependency conflict

### ISSUE THREAD

**Issue by jaisnan** [model-checking/kani#2880]
Extension of the issue on `cbmc-viewer`:
https://github.com/model-checking/cbmc-viewer/issues/146

**Comment by jaisnan** [comment]
Related PR: https://github.com/model-checking/cbmc-viewer/pull/147 
&
https://github.com/model-checking/kani/pull/2879

**Comment by tautschnig** [comment]
Closing as all related PRs have been merged (both in Kani as well as in CBMC Viewer).
