### ISSUE TITLE
Allow specifying CBMC custom flags from the command-line

### ISSUE THREAD

**Issue by pwnorbitals** [model-checking/kani#2887]
**Proposed change:** Allow specifying CBMC custom flags from the command-line

**Motivation:** In my case, CBMC hangs and I'm having a hard time understanding why. Giving a verbosity flag to `cbmc` would help me troubleshoot it wihtout recompiling Kani and needed a full dev environment.

**Comment by zhassan-aws** [comment]
Hi @pwnorbitals. Thanks for opening this issue. CBMC flags can be specified using `--enable-unstable --cbmc-args <CBMC-FLAGS>`, e.g. `--enable-unstable --cbmc-args --verbosity 9`.

Kani processes the output from CBMC though, so you may not see what you're looking for. If you want to disable the processing of output, you can run with `--output-format old`.

**Comment by pwnorbitals** [comment]
Ah, nice ! My apologies, I missed this in the help page.
