### ISSUE TITLE
Feature request: detect when object layouts may not faithfully follow Rustc layouts

### ISSUE THREAD

**Issue by danielsn** [model-checking/kani#296]
RMC aims to be a bit-precise model of the Rust semantics. In particular, we aim to be layout compatible with the objects generated by the Rust compiler. This is important because the implementation of some code depends on precise object layouts, including:

* FFI calls
* Some unsafe optimizations in the standard library
* globally allocated data.

If we do not faithfully model object layouts, this code will give spurious results. 

* For example, globally allocated data is initialized using a byte-pattern. If the object layout does not match the expected layout, global data will be invalidly initialized. 
* The standard library often takes advantage of objects with matching layouts to transmute between objects. 
* We need to ensure that the sizeof of an object calculated in Rust matches the sizeof of the object in CBMC 

## Likelihood:

Given the lack a precise formal spec for object layouts, it is difficult to ensure that we have correctly handled all cases. In particular, Rust has a number of features that make getting object layouts correct difficult: 

* Multiple representations (Transparent, C, Packed, etc)
* Niche optimizations
* Fat and thin pointers

## Mitigation: 

In places where there are obvious assertions (e.g. that transmute operations occur between objects of the same size), we have added those assertions. More generally, we have written tests that check functional properties reliant on object layout, such as FFI calls and standard library usage.

## Path to soundness:

Soundness would require a precise formal spec of object layouts. We can work with the compiler team to develop such a spec.

## Documentation:

https://doc.Rust-lang.org/reference/type-layout.html (https://doc.rust-lang.org/reference/type-layout.html)

**Comment by zhassan-aws** [comment]
Can we indicate in the docs that Kani is assuming a specific version of the compiler, and that results are correct with respect to that version since layouts may change with a different version?
