### ISSUE TITLE
Kani should fail due to invalid access of a dead local variable via raw pointer

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#3061]
I tried this code:
```rust
#[kani::proof]
pub fn check_invalid_ptr() {
    let raw_ptr = {
        let var = 10;
        &var as *const _
    };
    // This should fail since it is de-referencing a dead object.
    assert_eq !(unsafe {*raw_ptr}, 10);
}

```

using the following command line invocation:

```
kani invalid_ptr.rs
```

with Kani version: 0.47

I expected to see this happen: Verification should fail since the de-referenced pointer is pointing to a dead object.
Instead, this happened: Verification succeeds

**Comment by celinval** [comment]
BTW, I believe the problem here is that we don't encode stack variable liveness, so CBMC is no aware that this stack variable is dead. @tautschnig / @remi-delmas-3000 what's the correct way for us to encode this information in goto-programs?

**Comment by tautschnig** [comment]
If Kani produces blocks, then goto-program conversion will take care of this. So the question is: does Kani produce code blocks? Else, CBMC has no way of knowing when a variable goes out of scope. Kani could also directly produce non-deterministic updates to the `__CPROVER_dead_object` variable, but I don't think that makes for great design.

**Comment by tautschnig** [comment]
Looking at the MIR output for this example, however, it's not clear to me that `var` actually goes out of scope. My reading of the MIR output is that its lifetime is that of the function.

**Comment by celinval** [comment]
The MIR does include `StorageLive`/`StorageDead` statements, but it looks like they are removed by default. One possible way to enable it is by configuring the memory sanitizer via `-Zsanitizer=memory`
