### ISSUE TITLE
`kani` placeholder crate on crates.io

### ISSUE THREAD

**Issue by Turbo87** [model-checking/kani#3194]
While looking for name-squatting crates on crates.io I've found http://crates.io/crates/kani, but I assume that this might be a legitimate placeholder to avoid typo-squatting attacks. To prevent this placeholder from accidentally being deleted in the future it would be great if you could adjust the crate description and include a readme file explaining the purpose of this placeholder crate e.g. with a link to this repository.

**Comment by zhassan-aws** [comment]
Thanks @Turbo87. Makes sense. We will add a readme and a description.

**Comment by remi-delmas-3000** [comment]
Hi, @Turbo87 we just pushed an new version of the placeholder crate on crates.io. The README is minimal but now links to the this github repo and doc. Is that sufficient?

**Comment by Turbo87** [comment]
yep, thanks
