### ISSUE TITLE
Contract fails due to promoted constants being havocked

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#3228]
I tried this code:

```rust
extern crate kani;

#[derive(PartialEq, Eq)]
pub enum Foo {
    A,
    B,
}

#[kani::ensures(result == Foo::A)]
pub fn a() -> Foo {
    Foo::A
}

#[kani::proof_for_contract(a)]
fn check() {
    let _ = a();
}
```

using the following command line invocation:

```
kani enum_ensures_bug.rs -Zfunction-contracts
```

with Kani version: 7bf23a25dd3

I expected to see this happen: Verification succeeds

Instead, this happened:
```
SUMMARY:
 ** 1 of 1336 failed
Failed Checks: result == Foo::A
 File: "enum_ensures_bug.rs", line 9, in a_check_7b31b

VERIFICATION:- FAILED
Verification Time: 1.9666983s
```

**Comment by zhassan-aws** [comment]
This occurs with structs as well, e.g.
```rust
extern crate kani;

#[derive(PartialEq, Eq)]
pub struct Foo {
    x: i32,
}

#[kani::ensures(result == Foo { x: 5 })]
pub fn a() -> Foo {
    Foo { x: 5 }
}

#[kani::proof_for_contract(a)]
fn check() {
        let _ = a();
}
```

```

SUMMARY:
 ** 1 of 1334 failed
Failed Checks: result == Foo { x: 5 }
 File: "ensures_struct.rs", line 8, in a_check_7d30f5

VERIFICATION:- FAILED
Verification Time: 1.9546859s
```

**Comment by zhassan-aws** [comment]
The same occurs with tuple structs:
```rust
extern crate kani;

#[derive(PartialEq, Eq)]
pub struct Foo(i32);

#[kani::ensures(result == Foo(5))]
pub fn a() -> Foo {
    Foo(5)
}

#[kani::proof_for_contract(a)]
fn check() {
        let _ = a();
}
```

```
SUMMARY:
 ** 1 of 1334 failed
Failed Checks: result == Foo(5)
 File: "ensures_struct.rs", line 6, in a_check_b53d87

VERIFICATION:- FAILED
Verification Time: 1.9567466s
```

**Comment by zhassan-aws** [comment]
This version works:
```rust
extern crate kani;

#[derive(PartialEq, Eq)]
pub struct Foo {
    x: i32,
}

impl Foo {
    pub fn new(x: i32) -> Foo {
        Foo { x }
    }
}

#[kani::ensures(result == Foo::new(5))]
pub fn a() -> Foo {
    Foo::new(5)
}

#[kani::proof_for_contract(a)]
fn check() {
        let _ = a();
}
```
```
SUMMARY:
 ** 0 of 1337 failed

VERIFICATION:- SUCCESSFUL
Verification Time: 1.9658625s
```

**Comment by celinval** [comment]
This ensures seems to fail, which makes me think that this could be something weird is going on with promoted constants:
```rust
#[kani::ensures(Foo::A != Foo::B)] 
```

**Comment by zhassan-aws** [comment]
This one fails with the struct version as well:
```rust
#[kani::ensures(Foo { x: 3 } != Foo { x: 5 })]
```

**Comment by pi314mm** [comment]
I expanded the macros for the following test:
```rust
#[derive(PartialEq, Eq)]
enum Foo {
    A,
    B,
}

#[kani::ensures(|_| Foo::A != Foo::B)]
fn a() {
}

#[kani::proof_for_contract(a)]
fn check() {
  a();
}
```
Then simplified the expansion into this:
```rust
#[derive(PartialEq, Eq)]
enum Foo {
    A,
    B,
}

#[kanitool::checked_with = "check"]
#[kanitool::replaced_with = "b"]
#[kanitool::inner_check = "b"]
fn a() {}

#[allow(dead_code, unused_variables, unused_mut)]
fn check() {
    static mut REENTRY: bool = false;
    if unsafe { REENTRY } {}
    else {
        let _ = b();
        kani::assert(Foo::A != Foo::B, "Foo::A != Foo::B")
    }
}

fn b() {}

#[allow(dead_code)]
#[kanitool::proof_for_contract = "a"]
fn harness() { kani::internal::init_contracts(); { a(); } }
```
and this still causes the same error.

It seems like the error doesn't happen within the macro expansion, but within the `kanitool::checked_with = "check"` attribute. Surprisingly (since this function doesn't have any arguments), if we add `#[kanitool::proof]` to the `check` function, the test passes. It seems we are doing something for the `kanitool::proof` attribute that we aren't properly doing for the `kanitool::checked_with`.

**Comment by celinval** [comment]
Something is very weird... I created the following code:
```rust
extern crate kani;
use kani::Arbitrary;

#[derive(PartialEq, Eq, kani::Arbitrary)]
pub struct Foo(u8);

#[kani::requires(foo == Foo(1))]
pub fn foo_a(foo: Foo) -> Foo {
    kani::assume(foo == Foo(1));
    assert!(foo.0 == 1);
    foo
}

#[kani::proof_for_contract(foo_a)]
fn check_contract() {
    foo_a(kani::any());
}

#[kani::proof]
fn check_call() {
    foo_a(kani::any());
}
```

For some very weird reason, the `check_contract` fails but the `check_call` succeeds.

**Comment by celinval** [comment]
I think I know what's going on here! The problem is that CBMC is setting all static variables to nondet when we are enabling contracts. :facepalm:

I remember we had to add `--nondet-static-exclude` for the recursion tracker. It looks like we have to do that for every constant allocation. :cry:

**Comment by celinval** [comment]
@remi-delmas-3000 how does CBMC handles static strings? Is there anyv way we can mark an allocation constant?

**Comment by remi-delmas-3000** [comment]
Some explanations on what is going on: anonymous constants like `Foo(1)` that appear inline in expressions and are not bound using a `let` get lifted to const statics by the rustc compiler. 

So this 
```C
#[kani::requires(foo == Foo(1))]
pub fn foo_a(foo: Foo) -> Foo {
    kani::assume(foo == Foo(1));
    assert!(foo.0 == 1);
    foo
}
```

becomes something like this:
```Rust
static STATIC_FOO1 = Foo(1);

#[kani::requires(foo == Foo(1))]
pub fn foo_a(foo: Foo) -> Foo {
    kani::assume(foo == *&STATIC_FOO1);
    assert!(foo.0 == 1);
    foo
}
```

Static symbols like `STATIC_FOO1` are havoced by CBMC when contracts are applied, unless you explicitly say they should not using the `--nondet-static-exclude` flag, if you set the `ID_C_no_nondet_initialization` boolean tag on the `Irep` representing the type or the value of the static symbol.

**Comment by celinval** [comment]
https://github.com/rust-lang/const-eval/blob/master/promotion.md
