### ISSUE TITLE
Uninitialized memory detection mitigates delayed UB, but does not support it fully

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#3324]
I tried this code:

```rust
#[kani::proof]
fn invalid_value() {
    unsafe {
        let mut value: u128 = 0;
        let ptr = &mut value as *mut _ as *mut (u8, u32, u64);
        *ptr = (4, 4, 4);   // This assignment itself does not cause UB...
        assert!(value > 0); // ...but this reads a padding value! ⚠️
    }
}

```

using the following command line invocation:

```
kani -Z ghost-state -Z uninit-checks delayed-ub.rs
```

with Kani version: 0.53

I expected to see this happen: Verification should fail since we are reading padding values.

Instead, this happened: Verification succeed

**Comment by artemagvanian** [comment]
#3332 mitigated the issue: now all mutable pointer casts of unsupported padding are rejected
