### ISSUE TITLE
Kani Setup Fail MacOS

### ISSUE THREAD

**Issue by zi0Black** [model-checking/kani#3335]
`cargo kani setup` on MacOS fails to download the latest release because the file in the release contains `.zip` in the tail.

```
[0/5] Running Kani first-time setup...
[1/5] Ensuring the existence of: /Users/z0b/.kani/kani-0.53.0
[2/5] Downloading Kani release bundle: kani-0.53.0-aarch64-apple-darwin.tar.gz
curl: (22) The requested URL returned error: 404
Error: Failed to download Kani release bundle

Caused by:
    Failed command: curl -sSLf -o /Users/z0b/.kani/kani-0.53.0-aarch64-apple-darwin.tar.gz https://github.com/model-checking/kani/releases/download/kani-0.53.0/kani-0.53.0-aarch64-apple-darwin.tar.gz
```
![image](https://github.com/model-checking/kani/assets/13380579/926aa3c4-5508-462f-8c57-77022770f407)

with Kani version: 0.53

**Comment by jaisnan** [comment]
Will take a look at this. Thanks for the report.

**Comment by jaisnan** [comment]
I have replaced the problematic release bundle with a functioning replacement. Let us know if the setup works on your end now.

**Comment by zi0Black** [comment]
@jaisnan works :)
