### ISSUE TITLE
RMC omits some constant assertions (optimizations?)

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#337]
This could be (indirectly) a serious problem because it means some of our test cases may not be testing our translations to goto-c, instead getting rewritten away by optimizations applied purely within rustc.

This code:

```rust
struct Pair(i32, i32);

fn main() {
    let x = Pair(1, 2);

    assert!(0 == 0);
    assert!(1 == 1);
    assert!(x.0 == 1);
    assert!(x.1 == 2);
}
```

produces these assertions:

```
** Results:
/home/ubuntu/rmc/mytest.rs function main
[main.assertion.1] line 9 assertion failed: x.0 == 1: SUCCESS
[main.assertion.2] line 10 assertion failed: x.1 == 2: SUCCESS
```

This shows some constant propagation / dead code / partial evaluation going on. With such simple constant assertions disappearing, it might not be concerning, but re-ordered variants show bizarre behavior:

```rust
    assert!(x.0 == 1);
    assert!(x.1 == 2);
    assert!(0 == 0);
    assert!(1 == 1);
```

gives just one (no other assertions):

```
[main.assertion.1] line 8 assertion failed: x.1 == 2: SUCCESS
```

The `x.0` assertion has been optimized away as well now. Order matters:

```rust
    assert!(x.1 == 2);
    assert!(x.0 == 1);
    assert!(0 == 0);
    assert!(1 == 1);
```

```
[main.assertion.1] line 8 assertion failed: x.0 == 1: SUCCESS
```

So these simple variations seem to show:

1. very simple assertions always disappearing (we never see `1 == 1` in our goto-c, regardless of order)
2. Some (?? First? Early?) slightly less simple assertions vanishing sometimes.

I don't think this has direct soundness implications for our users (worst case: bug in rustc, but we all have to trust that anyway), but this is something we should figure out how to disable at least for our test suites to ensure we're actually testing all the translations we think we're testing.

**Comment by celinval** [comment]
Have you tried disabling optimizations on rustc? I agree that this may give us a false idea of feature coverage so it's not ideal in our regression. Maybe we should add an option to rmc to disable compiler optimizations.

**Comment by zhassan-aws** [comment]
Could not reproduce with `af11d38d93a`. Will add a regression and close.
