### ISSUE TITLE
Update overflow-checks option

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#3624]
This is a follow up from the discussion in #3620.

Requested feature: Kani's options to enable/disable overflow:
```
$ kani --help | grep overflow
      --overflow-checks
          Turn on default overflow checks
      --no-overflow-checks
          Turn off default overflow checks
```
give the impression that they're relevant to all types even though they only control overflow for floating-point types: https://github.com/model-checking/kani/blob/c5a4aea0c5e0c56fb86a8b0b9bb9733c2508729e/kani-driver/src/call_cbmc.rs#L193

We need to either change the option name to `float-overflow-checks` or just `float-checks` (since it also controls CBMC's `--nan-check`) or at least update the help to clarify that the option only applies to floating-point checks.

**Comment by celinval** [comment]
Why not remove float overflow checks in the first place? They are well-defined operations in Rust and they can be programmatically checked.

**Comment by zhassan-aws** [comment]
Agreed. I'll close this issue.
