### ISSUE TITLE
Failed to build kani from source on MacOS

### ISSUE THREAD

**Issue by QinyuanWu** [model-checking/kani#3643]
I'm trying to build kani from source by following [this](https://model-checking.github.io/kani/build-from-source.html) tutorial. When I run the command `./scripts/setup/macos/install_deps.sh` I received the following error:
```
==> Fetching aws/tap/cbmc-viewer
==> Downloading https://files.pythonhosted.org/packages/91/a5/429efc6246119e1e3fbf562c00187d04e83e54619249eb732bb423ef
Already downloaded: /Users/owo/Library/Caches/Homebrew/downloads/9459b28e4118d509c4c03ad0168a5c125d5446c824380fd5bb36050751f4f465--Jinja2-3.0.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51
Already downloaded: /Users/owo/Library/Caches/Homebrew/downloads/2f2488b4acce3f0f78d8d8a234cbcc0306b6789e9b18ada8269380a59131b350--MarkupSafe-2.0.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/c0/2c/ccbeb25364e3e0c5e4522f13d66e2fc639bb4d4ecdf73be0959552cb
Already downloaded: /Users/owo/Library/Caches/Homebrew/downloads/6835d2f459443cbf0e67e6594b69166c11a87e34b60785c79372505a8f535a42--voluptuous-0.12.2.tar.gz
==> Cloning https://github.com/model-checking/cbmc-viewer.git
Updating /Users/owo/Library/Caches/Homebrew/cbmc-viewer--git
==> Checking out tag viewer-3.9
HEAD is now at a35eb35 Second attempt to fix update-pr
HEAD is now at a35eb35 Second attempt to fix update-pr
==> Installing cbmc-viewer from aws/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 16.0.
```

I checked my Xcode version is 16.0(downloaded it manually) and `xcode-select -p` shows that it is pointing to the correct Xcode path:
```
% xcode-select --print
/Applications/Xcode.app/Contents/Developer # I've also tried point it to /Library/Developer/Commandlinetools but got the same error
% xcode-select --version
xcode-select version 2409.
```
![image](https://github.com/user-attachments/assets/50ae581e-8204-4ad6-947c-552c5bc63289)
Platform: MacOS Sequoia 15.0.1(latest version, the error also occurred before I did the system update) M2 
Homebrew version: 4.4.2
Appreciate if there is any guidance on how to resolve this. Thank you!
@zhassan-aws

**Comment by carolynzech** [comment]
This seems to be more of a Homebrew issue than a Kani issue, but we'll do our best to help. Have you tried running the `sudo` commands that the help message suggests? There is some discussion in [this Homebrew issue](https://github.com/Homebrew/brew/issues/4101) about the same problem, so you could try the steps there. If I had to guess, I'd say that the script can't find the PATH to this more recent version of XCode (and is finding an older installed version instead), so I'd try to investigate in that area.

**Comment by QinyuanWu** [comment]
@carolynzech Thank you for the suggestions. I tried all the above and the issue persisted and after investigating the script the error occured at this step to build `cbmc-viewer` from source:
```
brew install -s aws/tap/cbmc-viewer
```
I ended up following the cbmc-viewer installation [guide](https://model-checking.github.io/cbmc-viewer/installation/) and did:
```
  brew tap aws/tap
  brew install cbmc-viewer universal-ctags
  brew upgrade cbmc-viewer
```
and then installed `kissat` through `/scripts/setup/install_kissat.sh` and followed through the rest of the kani set up tutorial, and I am able to use the build-from-source version of kani for verification.
