### ISSUE TITLE
Implement `Arbitrary` for `Range*`

### ISSUE THREAD

**Issue by c410-f3r** [model-checking/kani#3662]
The `Arbitrary` trait is not implemented for the set of range-like structures.

* Range
* RangeFrom
* RangeFull
* RangeInclusive
* RangeTo
* RangeToInclusive

The lack of such a feature mandates the manual rolling of intended parameters.

```rust
#[kani::proof]
fn foo() {
let start = kani::any();
let end = kani::any();
let _ = std::ops::RangeInclusive::<u8>::new(start, end));
```

**Comment by zhassan-aws** [comment]
Hi @c410-f3r. Thanks for the feature request. This shouldn't be difficult to add. If you would like to contribute the implementation, we would be happy to provide guidance.
