### ISSUE TITLE
Running `--visualize` still includes unnecessary CBMC checks in coverage run

### ISSUE THREAD

**Issue by vecchiot-aws** [model-checking/kani#368]
With working directory as `src/test/cbmc/LoopLoop_NonReturning`:

The following works fine:
`rmc main.rs --cbmc-args --unwind 10`

The following does not terminate:
`rmc --visualize main.rs --cbmc-args --unwind 10`

When I manually set `cover_args` to `["--unwind", "10"]`, it terminates successfully.

Possible solution: add `--unwind` as an RMC flag, and if present, add it to `cover_args` as well.

**Comment by zhassan-aws** [comment]
@tedinski, this is also fixed by #738. We might want to add a regression for it though.

**Comment by tedinski** [comment]
It's sort of fixed, yes. The completely perfect fix will remove the `--blah-checks` flags from the `--cover` run, which I punted for a follow up PR. Adding a test is a good idea, too.

**Comment by celinval** [comment]
Closing this since we are now deprecating `--visualize` option.
