### ISSUE TITLE
Add support for dev setup on Ubuntu 24.04

### ISSUE THREAD

**Issue by rafaelsamenezes** [model-checking/kani#3728]
The [install-cbmc.sh](https://github.com/model-checking/kani/blob/main/scripts/setup/ubuntu/install_cbmc.sh) is supposed to get the correct .deb from Diffblue release or build one when it is not available. The issue is that the script is trying to download cbmc for ubuntu 24.04 while the [available releases](https://github.com/diffblue/cbmc/releases/tag/cbmc-6.4.0) are for 20.04 or 22.04.

**Comment by celinval** [comment]
That's a good point. I don't think we have dev support for Ubuntu 24.04. We need to add a setup script and a CI job.

**Comment by tautschnig** [comment]
The CBMC-specific problem has been addressed on the CBMC side (https://github.com/diffblue/cbmc/releases/download/cbmc-6.4.1/ubuntu-24.04-cbmc-6.4.1-Linux.deb now exists with automation for Ubuntu 24.04 having been put in place), but we should still add the CI part on the Kani side.
