### ISSUE TITLE
Create `rmc_log` and `rmc_warn` macros

### ISSUE THREAD

**Issue by vecchiot-aws** [model-checking/kani#382]
These macros will write both to stdout and to a log file in a structured format so we can extract information from them in a procedural way in post-processing. See #350, for example.

**Comment by celinval** [comment]
I'm not sure I understand the reasoning behind writing logs to a json file. What's the use case we are trying to address?

**Comment by tedinski** [comment]
Is there anything else to do here then? Or can this be closed?

**Comment by celinval** [comment]
Maybe close it.
