### ISSUE TITLE
Reduce code duplication between `litani` and `compiletest`.

### ISSUE THREAD

**Issue by bdalrhm** [model-checking/kani#390]
Code in `src/tools/dashboard/src/util.rs` contains a lot of code copied from `compiletest`. We should consider porting all the tests from `compiletest` to `litani`. This will give us the benefit of having a unified interface for both test suites and examples from Rust books.

**Comment by adpaco-aws** [comment]
This isn't needed anymore (see https://github.com/model-checking/kani/pull/3123).
