### ISSUE TITLE
Add a new option to run visualize without coverage

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#410]
Requested feature: A new option that can be used for extracting the counterexample trace without turning on coverage.
Use case: RMC's `--visualize` option can be very time consuming in some cases because it turns on coverage. In cases where the user is only interested in a counterexample trace, incurring the cost of turning on coverage might be undesirable.
Link to relevant documentation (Rust reference, Nomicon, RFC):
Is this a breaking change?

Test case:

**Comment by zhassan-aws** [comment]
It seems that a new change on the RMC script side is not sufficient as cbmc-viewer expects a coverage file (if not specified explicitly with `--coverage` cbmc-viewer assumes the default filename `coverage.xml`).

**Comment by celinval** [comment]
Closing this since we are now deprecating `--visualize` option.
