### ISSUE TITLE
Pass appropriate unwind value for examples extracted from the Rust books.

### ISSUE THREAD

**Issue by bdalrhm** [model-checking/kani#419]
Several example configurations pass `--cbmc-args --unwind 0` to RMC. An unwind value of 0 is passed because, for some reason, Litani does not terminate/kill processes that reach the timeout value (10 seconds). Replace 0 with appropriate values when this issue gets fixed.

**Comment by zhassan-aws** [comment]
@adpaco-aws is this issue still relevant?
