### ISSUE TITLE
Avoid `pub` declarations due to linking issues with `librustdoc`

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#461]
In #447 we changed the qualifier of some components in `librustdoc` from `crate` to `pub` due to linking issues. This may cause conflicts in the future that we would like to avoid.

**Comment by celinval** [comment]
I'm closing this since we have forked librustdoc and we are planing to clean up the code that is irrelevant to us. Please feel free to reopen if you think this is still relevant.
