### ISSUE TITLE
Cargo rmc fails with crate-type bin (and tests)

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#473]
When a local crate is used as a dependency in another binary crate, `cargo rmc` produces an error of the form:
```
extern location for ... does not exist
```

Steps to reproduce:

1. Create a temporary directory:
```
mkdir tmp && cd tmp
```
 2. Create two crates:
```
cargo new --lib foo
cargo new bar
```
 3. Add foo as a dependency in bar's `Cargo.toml`:
```
[dependencies]
foo = { path = "../foo" }
```

 4. Add `use foo;` in bar's `src/main.rs`
 5. Run
```
RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo build --target x86_64-unknown-linux-gnu
```

with RMC version: nightly

This produced the following error:
```
$ RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo build --target x86_64-unknown-linux-gnu
   Compiling foo v0.1.0 (/home/ubuntu/examples/tmp/tmp/foo)
   Compiling bar v0.1.0 (/home/ubuntu/examples/tmp/tmp/bar)
error: extern location for foo does not exist: /home/ubuntu/examples/tmp/tmp/bar/target/x86_64-unknown-linux-gnu/debug/deps/libfoo-59942b648e7fcc3e.rlib
 --> src/main.rs:1:5
  |
1 | use foo;
  |     ^^^

error: aborting due to previous error

error: could not compile `bar`

To learn more, run the command again with --verbose.
```
If `bar` is created as a library instead, it works.

**Comment by celinval** [comment]
I believe we need to be able to generate `.rlib` files.

**Comment by celinval** [comment]
I believe I figured out the root cause. The issue here is not with local crates but with binary crates. 

1. Test still fails if you replace the dependency by an external crate.
2. Test succeeds if you change step 2 to:

```
cargo new --lib foo
cargo new --lib bar
```

I compared the runs with and without the `--lib` in the step 2. For the library target, cargo sets the dependencies (`--extern`) using metadata files (`.rmeta`), but for binary target, it will use `.rlib` files. We generate the former but not the latter.

**Comment by tedinski** [comment]
Darn. I was hoping `--tests` might fix it, but it seems that tests are ultimately built in binary mode and so `--tests` actually re-triggers the issue even when using `--lib` on both.

**Comment by tedinski** [comment]
This is especially high-priority, since lack of `--tests` means people have to build with normal `cargo build`, and therefore if they need a `dev-dependency`, it must be moved to be a regular `dependency` to be available, which is horrible.
