### ISSUE TITLE
RMC-rustc interface: Existing RMC interface to rustc

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#51]
Inventory of how we're currently hooked in (what features we use)

**Comment by tedinski** [comment]
I think this was an accidental closure because we merged a commit from rustc that said "fixes #51" in it?

There's a new threat model to watch out for, hah

**Comment by celinval** [comment]
Oops. Good catch @tedinski!

**Comment by adpaco-aws** [comment]
Closing this issue since we now have a good idea about this topic and have a plan in progress to properly interface with `rustc` (see #719 to see what steps have been taken to improve it until now).
