### ISSUE TITLE
Demangling of variable names

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#59]
Can we track the name of variables so we get
`main::square::vol` instead of `main::Shape[0]::vtable main$$Shape[0]$$vtable_impl_for_&main$$Rectangle[0]`?

**Comment by vecchiot-aws** [comment]
Track on https://github.com/vecchiot-aws/rmc/tree/demangled_names.

**Comment by tedinski** [comment]
@adpaco-aws is this resolved now with #1303 and such?

**Comment by zhassan-aws** [comment]
This was resolved in #1303.
