### ISSUE TITLE
Ensure we are building the right machine model from a session

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#64]
In particular, should char be signed? What should the rounding mode be?

**Comment by adpaco-aws** [comment]
The actual concern here is that we are hardcoding values in `machine_model_from_session` (in `src/kani-compiler/src/codegen_cprover_gotoc/context/goto_ctx.rs`. We definitely want to get these values from the session instead of doing that.

**Comment by zhassan-aws** [comment]
Check if the target architecture agrees with the hardcoded values. If not, throw an error.
