### ISSUE TITLE
Boogie backend

### ISSUE THREAD

**Issue by HKalbasi** [model-checking/kani#640]
## What is boogie?

[Boogie](https://github.com/boogie-org/boogie) is an intermediate verification language (IVL), intended as a layer on which to build program verifiers for other languages. If I understand correctly, it would enable `rmc::non_det` to support all structures (for example strings and vectors) but it would need to annotate all functions with preconditions and postconditions.

## Isn't it out of scope?

Maybe it is. But if we imagine a separate project for verification via boogie, it would need similar things to `rmc::non_det` (boogie's havoc) and `rmc::assume` and ... . And in future [loop invariants](https://model-checking.github.io/rmc/tutorial-loops-unwinding.html) and function contracts (pre/post conditions). Keeping this annotations the same can enable using both of CBMC and boogie at the same time, proof some methods via model checking and use them in boogie proofs. So integrating both in the same project has some benefits.

**Comment by danielsn** [comment]
This is a very exciting idea - the SMACK https://smackers.github.io/ project uses boogie, and has seen success verifying rust, so we'd definitely love to try boogie as an additional backend.  https://github.com/viperproject/prusti-dev is another project that is looking at using a function-contract based backend for Rust.

Currently we are focusing on improving rust language coverage, as well as the user experience of RMC.  Improving / switching out backends is a great area for future work.

RMC is a community project: if you're interested in building out new features, we'd love to have you join us.  PRs are always welcome :)

Also, we are hiring summer interns.

**Comment by HKalbasi** [comment]
Smack and Prusti are nice projects that I wasn't aware of. Point of this issue is to interoperate `rmc` with a function-contract based backend. Since some of them exists now, problem would be how to interoperate between `rmc`, `prusti` and `smack`.

I see parallel things for non_det, assume, loop invariants and function contracts. A tool agnostic crate (for example rust_spec) can provide these with user experience in mind. It would enable using more than one verification method for a project (as above), and a project can depend on a project with different verification method. For example it isn't reasonable for std to annotate each function and loop for every verification tool, but it probably can do it for a unified rust_spec.

**Comment by DavePearce** [comment]
Hey,

Interesting to see this thread!  I have experience developing a Boogie backend for Whiley (see [here](https://github.com/Whiley/Whiley2Boogie/)) so happy to provide suggestions, comments, help, etc.  In general, I think it would be a big departure from how RMC is currently working.  The need to annotate is a key challenge, and I wonder if it can be avoided.  For example, I'm not sure how they are using it in SMACK?

**Comment by zhassan-aws** [comment]
We don't have plans to add a Boogie backend at the moment. Closing this issue.
