### ISSUE TITLE
Possibly broken tests

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#677]
These tests are apparently succeeding, but are possibly actually crashing CBMC:

* `src/test/rmc/DynTrait/drop_nested_boxed_dyn_fail.rs`
* `src/test/rmc/DynTrait/dyn_fn_mut_fail.rs`
* `src/test/rmc/DynTrait/dyn_fn_once_fail.rs`
* `src/test/rmc/DynTrait/nested_closures_fail.rs`

**Comment by zhassan-aws** [comment]
With `af11d38d93a` and CBMC 5.52.0, none of the tests mentioned above are crashing. Closing this issue.
