### ISSUE TITLE
Consider turning off CBMC vtable size check assert by default

### ISSUE THREAD

**Issue by avanhatt** [model-checking/kani#682]
We added this check for ensuring we build vtables and translate them to GotoC correctly, but this can cloud user output with assertions they did not add. We should consider turning this off by default, and make it a "debug"/"developer" or similar option.

`Correct CBMC vtable size for...`

See also: `assert_sanity_check`.

**Comment by tedinski** [comment]
Closing this. We hide sanity checks by default from user-visible output. So I think this concern ("this can cloud user output with assertions they did not add") is resolved.
