### ISSUE TITLE
RMC libraries should be build and put into a standard place

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#720]
**Requested change:** We should ensure that RMC libraries are built and placed in a standard place for rmc-compiler find them without relying on rmc-rustc script. Ideally, this solution should also work with `cargo install`. We should keep supporting the --rmc-lib argument in the rare cases the user wants to override this configuration.

**Use case:** Improve installation of RMC.

**Is this a breaking change?** No

This issue depends on #719

**Comment by tedinski** [comment]
I believe this was resolved when we built the installation process.
