### ISSUE TITLE
Improve rmc-compiler configuration when using cargo rmc

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#721]
**Requested change:** Figure out a better mechanism to pass arguments from cargo rmc to rmc-compiler.

**Use case:** The rmc-rustc  handles the hack to connect cargo rmc to rmc. We should investigate a more reliable mechanism that doesn't rely on environment variables.

Note: I tried to bundle the options as a sub-option but cargo doesn't seem to handle quotes very well.

**Is this a breaking change?** No

**Comment by tedinski** [comment]
Is this still an issue? Certainly `rmc-rustc` is gone...

**Comment by celinval** [comment]
Yes, this is still a problem. We should be passing arguments via RUSTC_FLAGS since `cargo` uses that information to compute whether a crate should be recompiled or not.

We will need to fix this in order to properly support incremental compilation.

**Comment by celinval** [comment]
Closing this since it will be fixed as part of #2137
