### ISSUE TITLE
Investigate how to remove temporary variables from verification report and traces

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#724]
**Requested feature:** We would like to scope the work to remove temporary variable names from RMC's verification report and trace.
**Use case:** User should be able to read RMC's verification result and easily map that to their original rust code.
**Link to relevant documentation (Rust reference, Nomicon, RFC):**
**Is this a breaking change?** No

**Comment by tautschnig** [comment]
You may be able achieve some of this by setting the `is_auxiliary` bit of symbols you'd like not to appear in the trace when generating the symbol table to pass to `symtab2gb`.

**Comment by celinval** [comment]
That's awesome! Thanks @tautschnig
