### ISSUE TITLE
Support for String-related issues

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#74]
We have a few unsupported String tests in:
```
rust-tests/cbmc-reg/Strings/fixme_boxed_str.rs
rust-tests/cbmc-reg/Strings/fixme_os_str.rs
rust-tests/cbmc-reg/Strings/fixme_main.rs
```

**Comment by zhassan-aws** [comment]
@adpaco-aws it seems that the tests no longer fail: fixme has been removed from `boxed_str.rs` and `os_str.rs`. For `fixme_main.rs`, kani reports one failure, but the test panics with rustc anyway. Should we close this issue?

**Comment by adpaco-aws** [comment]
Yes, but we should remove the test. `test2` in `fixme_main.rs` seemed interesting but there is similar code somewhere else.

Opened the PR to do that, please take a look.
