### ISSUE TITLE
Unimplemented intrinsic: `bitreverse`

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#745]
`bitreverse` is not supported at the moment.

It appears CBMC does not have available the `bitreverse` builtin according to [the irep IDs definitions](https://github.com/diffblue/cbmc/blob/develop/src/util/irep_ids.def). I will talk to CBMC folks to see what can be done about this, but another approach here is to implement the logic for bit reversal it in RMC.

**Comment by tautschnig** [comment]
I have created https://github.com/diffblue/cbmc/pull/6581, which does require further work until it can be merged, but might already suffice to clarify the interface for RMC to use.
