### ISSUE TITLE
Panic for `assert_inhabited` has no effect because of `Nevers` hook

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#751]
Related to #648.

Instead of executing the code for `assert_inhabited`, the `Nevers` hook is being applied. This causes the test introduced in #742 to fail with an unexpected property. The `Nevers` hook has to be removed at some point, this issue is for keeping track of that and going back to ensure the test is working as expected.

**Comment by zhassan-aws** [comment]
Blocked by #648

**Comment by celinval** [comment]
This error out now with:
```
Check 2: std::mem::MaybeUninit::<T>::assume_init.assertion.1
         - Status: FAILURE
         - Description: "attempted to instantiate uninhabited type `!`"
         - Location: TOOLCHAIN/library/core/src/mem/maybe_uninit.rs:633:13 in function std::mem::MaybeUninit::<T>::assume_init

```
