### ISSUE TITLE
Cleanup after `compiletest` move out of `x.py`

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#754]
Some places where a cleanup would be great:
 1. Either make a wrapper in `compiletest` (and other changes) to have a single call (i.e., passing the suite names as we did before) or add a script that gets called from `rmc-regression.sh`
 2. Remove references to our suites in bootstrap
 3. Remove optional arguments from `compiletest`

**Comment by celinval** [comment]
I wouldn't bother with 2, since we are soon going to remove all those files from our repo.

**Comment by zhassan-aws** [comment]
@adpaco-aws are any of the cleanup tasks still pending?

**Comment by adpaco-aws** [comment]
Yes, I think 3 is still pending.

**Comment by JanSvejda** [comment]
@adpaco-aws could you provide an example argument to remove for 3)? Do I understand 3) correctly as "remove all arguments that are not actually used in the Config on line 199 of `compiletest/main.rs`"? I would like to submit a PR

**Comment by adpaco-aws** [comment]
Hi @JanSvejda , thank you for your interest!

I think you've got a good understanding: the task in (3) would be focused on removing arguments not used in `Config`, in addition to removing the parsing of those arguments [here](https://github.com/model-checking/kani/blob/main/tools/compiletest/src/main.rs#L58). Hope that helps!
