### ISSUE TITLE
Ensure testing for `bitreverse` when support in CBMC is available

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#778]
Soon we will add partial support for the `bitreverse` intrinsic in Kani. CBMC does not support it but is being implemented in https://github.com/diffblue/cbmc/pull/6581

When support is available, fix any issues with our implementation and enable testing.

**Comment by tautschnig** [comment]
https://github.com/diffblue/cbmc/pull/6638 has been issued, so a release that includes support for `bitreverse` should be out before the end of the day.
