### ISSUE TITLE
Feature - Adding Property Classes Fields to Assertion Metadata

### ISSUE THREAD

**Issue by jaisnan** [model-checking/kani#793]
Requested feature: Add Property Classes to Assertion Metadata

Use case: 1) Allow Kani to dictate behavior and handling of different types of assertions depending on their property_class instead of handling all the assertions the same way. 
                  2) Users can query with unique assertion id's like - [main.property_class.1]

This requires changing how we codegen asserts. The symtab currently looks like - 

```json

"id": "side_effect",
"sub": [
{
"id": "symbol",
"namedSub": {
    "identifier": {
        "id": "__CPROVER_assert"
    },
    "#source_location": {
        "id": "",
        "namedSub": {
            "file": {
                "id": "/home/ubuntu/kani/library/kani/src/lib.rs"
            },
            "line": {
                "id": "86"
            },
            "column": {
                "id": "5"
            },
            "function": {
                "id": "kani::any_raw"
            },
        }
    },
    "type": {
        "id": "code",
        "namedSub": {
            "parameters": {
                "id": "",
                "sub": [
                    {
                        "id": "parameter",
                        "namedSub": {
                            "type": {
                                "id": "bool"
                            }
                        }
                    },
                    {
                        "id": "parameter",
                        "namedSub": {
                            "type": {
                                "id": "pointer",
                                "sub": [
                                    {
                                        "id": "signedbv",
                                        "namedSub": {
                                            "width": {
                                                "id": "8"
                                            }
                                        }
                                    }
                                ],
                                "namedSub": {
                                    "width": {
                                        "id": "64"
                                    }
                                }
                            }
                        }
                    }
                ]
            },
            "return_type": {
                "id": "empty"
            }
        }
    }
}
                
```

This is generated by a function that has a `function_call` statement - 

```rust
pub fn assert(cond: Expr, msg: &str, loc: Location) -> Self {
    assert!(cond.typ().is_bool());
    BuiltinFn::CProverAssert
        .call(vec![cond, Expr::string_constant(msg)], loc.clone())
        .as_stmt(loc)
}

```

This needs to be replaced by `assert` statement instead.

**Comment by zhassan-aws** [comment]
@jaisnan, based on what @tautschnig mentioned, we shouldn't be doing a function call, and should instead generate an assert statement. I'm referring to the `BuultinFn::Assert.call(...` in your snippet.

**Comment by tedinski** [comment]
I think the next step would be trying to find a _concrete_ example of what the output symbol table **should** look like.

I tried using `cbmc --show-symbol-table --json-ui file.out` to get the symtab of a simple C assert example for comparison but this doesn't seem to show the IR of functions? What's the right way to "decompile" a goto binary to symtab? I thought it was that command, but apparently not.

**Comment by jaisnan** [comment]
The output changes successfully when we replace the `function_call` with an `assert` statement, will need to work on adding custom strings to source location (property_class and msg) so that we can customize the `assertion ID`

```
** Results:
[assertion.1] Code generation sanity check: Correct CBMC vtable size for StructTag("tag-_4317141983261250885") (MIR type Closure(DefId(1:9147 ~ std[2f3c]::rt::lang_start::{closure#0}), [(), i8, extern "rust-call" fn(()) -> i32, (fn(),)])). Please report failures:
https://github.com/model-checking/kani/issues/new?template=bug_report.md: SUCCESS
[pointer_primitives.1] dead object in OBJECT_SIZE(&temp_0): SUCCESS
/home/ubuntu/kani/library/kani/src/arbitrary.rs function <T as kani::Arbitrary>::any
[<T as kani::Arbitrary>::any.assertion.1] line 17 resume instruction: SUCCESS

/home/ubuntu/test-property-class/test.rs function main
[main.test-property-class-Loc.1] line 7 assertion: FAILURE

** 1 of 4 failed (2 iterations)
VERIFICATION FAILED
```

**Comment by jaisnan** [comment]
From a design perspective, is it valid to change the Location Enum to add setters for the `property_class` and `comment fields`?

**Comment by tautschnig** [comment]
This symbol table excerpt above is too incomplete: it's missing the "namedSub" element at the top level (there's just the "sub" element). Can someone point me to the Rust code that is, for example, generating "return" statements? Or perhaps declarations? Both of which should be much closer to what the "assert" statement will need to look like.

**Comment by zhassan-aws** [comment]
> Can someone point me to the Rust code that is, for example, generating "return" statements?

https://github.com/model-checking/kani/blob/636bb80fca5ab24aa547fb8105ee4539b73ac8bf/src/kani-compiler/cbmc/src/irep/to_irep.rs#L406
