### ISSUE TITLE
Using Kani with a custom Rust toolchain

### ISSUE THREAD

**Issue by nchong-at-aws** [model-checking/kani#813]
Requested feature: Documentation for how to use Kani with a custom Rust toolchain
Use case: I would like to evaluate changes to the Rust Standard Library with Kani. This means having a local build of the Rust toolchain and having Kani link in my version of the standard library against programs being analyzed.
Link to relevant documentation (Rust reference, Nomicon, RFC): None
Is this a breaking change? No

Here's what almost works (using a fresh ubuntu 20 machine):

```bash
sudo apt-get update
sudo apt-get install clang ninja-build pkg-config libssl-dev

cd
git clone https://github.com/rust-lang/rust.git
cd rust
mkdir build
cd build
../configure \
  --target x86_64-unknown-linux-gnu \
  --enable-extended --enable-full-tools \
  --tools=cargo,rls,clippy,rustfmt,analysis,src
../x.py build
rustup toolchain link myrust build/x86_64-unknown-linux-gnu/stage1

cd
git clone https://github.com/model-checking/kani.git
cd kani
# edit rust-toolchain.toml to use channel = "myrust"
# go through Kani build instructions (https://model-checking.github.io/kani/install-guide.html)

# not sure why this is required but I get a shared library error with Kani if I don't do this:
export LD_LIBRARY_PATH=~/rust/build/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib:$LD_LIBRARY_PATH
```

Now if I run Kani on an example:
```bash
$ cd ~/kani
$ kani tests/expected/test1/main.rs
warning: `-Z symbol-mangling-version` is deprecated; use `-C symbol-mangling-version`

error: extern location for std does not exist: /home/ubuntu/kani/target/debug/build/kani-compiler-313dcd64face60e8/out/lib/libstd.rlib
```

If I rollback Kani to ea57abdef146 (prior to the change for the std wrapper crate) then the command above works.

**Comment by celinval** [comment]
I tried a slightly modified sequence of commands and it worked for me on Ubuntu 18.04. Instead of changing the rust-toolchain.toml, I created a directory override. Can you please check if that works for you?

Here is the sequence of steps:

```bash
# 1: Clone rust repository and build toolchain.
cd ${ROOT:?"Set this varible to a place where to clone Kani and Rust repo"}
git clone https://github.com/rust-lang/rust.git
pushd rust
./configure --enable-extended --tools=src,rustfmt,cargo --enable-debug --set=llvm.download-ci-llvm=true
./x.py build -i --stage 1 library/std;

# 2: Create a custom rustup toolchain named "myrust"
rustup toolchain link myrust build/x86_64-unknown-linux-gnu/stage1
popd

# 3: Clone and configure Kani
git clone https://github.com/model-checking/kani.git
pushd kani
# Run setup scripts

# 4: Override the rustup toolchain
rustup override set myrust

# 5: Build workspace
cargo clean # In case you have used this repository before. =)
cargo build

# 6: Test kani
kani tests/expected/test1/main.rs
```

**Comment by celinval** [comment]
BTW, I forgot to capture here that I checked out the commit that matches the version specified in the rust-toolchain.toml.

**Comment by nchong-at-aws** [comment]
Thanks Celina. This gets me much closer. I had to workaround two further errors at step 6:

```
# /home/ubuntu/kani/target/debug/kani-compiler: error while loading shared libraries: librustc_driver-a807dbe6f7d6f124.so: cannot open shared object file: No such file or directory
# a workaround is to use LD_LIBRARY_PATH:
export LD_LIBRARY_PATH=/home/ubuntu/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib
```

```
# error: extern location for std does not exist: /home/ubuntu/kani/target/debug/build/kani-compiler-313dcd64face60e8/out/lib/libstd.rlib
# a workaround is to copy things across
mkdir -p /home/ubuntu/kani/target/debug/build/kani-compiler-313dcd64face60e8/out/lib/
cp ./target/debug/*.rlib /home/ubuntu/kani/target/debug/build/kani-compiler-313dcd64face60e8/out/lib/
cp -r ./target/debug/deps /home/ubuntu/kani/target/debug/build/kani-compiler-313dcd64face60e8/out/lib/
```

---

For completeness, here's my build process which checks out the rust-toolchain corresponding to 2022-02-09 (what Kani currently uses):

```
# 0: dependencies for building rust
sudo apt-get update
sudo apt-get install clang ninja-build pkg-config libssl-dev

# 1: Clone rust repository and build toolchain
git clone https://github.com/rust-lang/rust.git
pushd rust
git checkout 9ad5d82f8 #<< this corresponds to 2022-02-09
./configure --enable-extended --tools=src,rustfmt,cargo --enable-debug --set=llvm.download-ci-llvm=true
./x.py build -i --stage 1

# 2: Create a custom rustup toolchain named "myrust"
rustup toolchain link myrust build/x86_64-unknown-linux-gnu/stage1
popd

# 3: Clone and configure Kani
git clone https://github.com/model-checking/kani.git
pushd kani
# Run setup scripts

# 4: Override the rustup toolchain
rustup override set myrust

# 5: Build workspace
cargo clean
cargo build

# 6: Test kani
kani tests/expected/test1/main.rs 
```

**Comment by celinval** [comment]
Let me debug this further. It looks like there's still something wrong with our build script. Thanks!

**Comment by celinval** [comment]
I figured out the std issue so far. The custom toolchain does not include the cargo even though we have built it so your system is using the default stable cargo. We require a cargo unstable option to be able to put the `rlib` files where we want them to be and the stable cargo just ignores that and do not copy the `rlib` files.

I could find two fixes for that:
1. You can manually copy the cargo binary to your stage1 folder to include in your custom toolchain. I.e.:
```
cp build/x86_64-unknown-linux-gnu/stage1-tools/bin/cargo build/x86_64-unknown-linux-gnu/stage1
```
2. You can install a nightly toolchain that includes cargo. If a component is missing while running a custom toolchain, rustup will default to one of the following nightly, beta, stable, in this order. That's why the instructions I gave you were working for me.

**Comment by celinval** [comment]
Ah, finally I figured it out. I believe we will need to use the stage2 compiler to create the toolchain. I noticed that in the stage 1 build, we had two different versions of `librustc_driver*.so`, which was the reason linking was not working properly.:
```bash
ubuntu@ec2:~/workspace/rust$ find build/x86_64-unknown-linux-gnu/stage1 -name librustc_driver*
build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-81eac465f0de4a8c.so
build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-a807dbe6f7d6f124.so
```
While stage 2 only has one version:
```bash
ubuntu@ec2:~/workspace/rust$ find build/x86_64-unknown-linux-gnu/stage2 -name librustc_driver*
build/x86_64-unknown-linux-gnu/stage2/lib/librustc_driver-a807dbe6f7d6f124.so
build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-a807dbe6f7d6f124.so
```

I also did some research to confirm my theory, and I found the following description on the [stage 2 compiler doc](https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html?highlight=state%202#stage-2).

> This means that the symbol names used in the compiler source may not match the symbol names that would have been made by the stage1 compiler, which can cause problems for dynamic libraries and tests.
>
> The stage2 compiler is the one distributed with rustup and all other install methods.

I will create a PR with the final instructions shortly. Cheers!

**Comment by nchong-at-aws** [comment]
Awesome, great sleuthing!
