### ISSUE TITLE
Dynamic and Ref(Dynamic) codegen to same fat pointer

### ISSUE THREAD

**Issue by markrtuttle** [model-checking/kani#82]
The method `codegen_ty` produces the same fat pointer for both the Dynamic and Ref(Dyanmic) mir type kinds.  I'm not sure what Dynamic should codegen since a trait object can only be accessed via a pointer (a fat pointer).  But probably no one should be trying to codegen Dynamic itself, and we should panic if anyone tries to do so.

**Comment by avanhatt** [comment]
In some cases where closures or function pointers are passed as arguments; it seems like we are codegening just a `Dynamic`.

**Comment by avanhatt** [comment]
Possibly related: https://github.com/model-checking/rmc/issues/95

**Comment by danielsn** [comment]
Appears to be related to projection issue
