### ISSUE TITLE
`--visualize` and `--output-format` don't play well together

### ISSUE THREAD

**Issue by danielsn** [model-checking/kani#820]
If you pass both `--visualize`, you just get a bunch of xml output, no matter what was passed as the `--output-format`

**Comment by jaisnan** [comment]
Will take a look at this, adding a quick fix by changing the flow a little bit. Same happens with `--dry-run` as well.

**Comment by tedinski** [comment]
I believe this was fixed by #738. Output format gets silently ignored when `--visualize` is set now.
