### ISSUE TITLE
CBMC's generated checks include temporary variables in their descriptions

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#874]
Kani relies on a few checks that are generated by CBMC. Those checks may contain messages that mention temporary variables which is not very helpful:

```
pointer arithmetic: pointer outside object bounds in (const char *)(void *)var_5 + (signed long int)(1 * var_6)
same object violation in (const char *)(void *)var_4 >= (const char *)(void *)var_5 + (signed long int)(1 * var_6)
```

This issue covers auto-generated cbmc checks.

**Comment by celinval** [comment]
For now, we can translate the CBMC check outputs (I believe they are all defined here: https://github.com/diffblue/cbmc/blob/develop/src/analyses/goto_check_c.cpp). That is quite fragile though. @tautschnig, is there a more reliable way today to remove these temporary variables from here?

We should also investigate whether we can start creating the checks ourselves with descriptions and IDs that we can easily control.

**Comment by celinval** [comment]
You are correct. They were created by Kani, but they were marked as auxiliary. I was hoping that case we could get a generic message without the actual expression.

Is there any way to reliably get what kind of check this is without having to match the error message? Unfortunately, the id seems too generic still.

**Comment by tautschnig** [comment]
Perhaps a rather unrelated bit of code of mine that is still work-in-progress could be of help: [src/goto-programs/goto_check.cpp](https://github.com/diffblue/cbmc/pull/6688/files#diff-7b9f6abb89c8594d143ff56839f46a184a9a0f3d92a4064bff70d7c06494a60a). That code is basically reverse-engineering the kind of check from the property class (which is the middle component of the id) and the prefix of the error message.
