### ISSUE TITLE
Cargo kani always rebuilds the entire project

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#895]
I tried the code inside `tests/cargo-kani/dependencies` using the following command line invocation:

```
cargo kani --function check_dummy
cargo kani --function check_dummy
```

with Kani version:

I expected to see this happen: *explanation*

Compilation should only execute once. In the second case, only CBMC should execute.

Instead, this happened: Cargo compiles the project and its dependencies every time we execute `cargo kani`.

**Comment by zhassan-aws** [comment]
@celinval: changed this from a bug to an enhancement. Let me know if you disagree.

**Comment by celinval** [comment]
That's OK.

**Comment by celinval** [comment]
This has been fixed by https://github.com/model-checking/kani/pull/2232
