### ISSUE TITLE
Kani trace includes wrong variable initializaton

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#897]
I tried this code:
```rust
fn main() {
  let var = kani::any::<u8>();
  if var == 0 {
      let temp = 1;
      kani::assert(temp > 0, "valid assert");
  }
  assert!(var == 0);
}

```
using the following command line invocation:

```
kani test.rs --visualize
```

with Kani version:

I expected to see this happen: The trace included assigning variable `var` once to a value different than `0`.
Instead, this happened: The execution includes two assignments to the variable var, the first one is `0`, which represents the variable initialization (following the C semantics), and the second correctly assigns a value that is different than `0`. This is confusing for a few reasons. First, var is not mutable, so the second assignment seems wrong. Second, in a few examples, the trace display the assignment to `temp = 1` even though it is not executed in the trace.

**Comment by tautschnig** [comment]
I believe that diffblue/cbmc#6712 would partly address this, with the remaining fix being a change to viewer so that it obeys the `hidden="true"` attribute of trace steps.

**Comment by celinval** [comment]
Closing this since we are now deprecating `--visualize` option.
