### ISSUE TITLE
Ubuntu and macOS regressions do not use the same CBMC version

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#933]
Our setup script for macOS does not control the CBMC version to be installed. This will cause confusing CI failures if there are bugs in the latest CBMC version, blocking contributions for a while (as in #928).

Instead, we should use a single, fixed CBMC version for both regressions.

**Comment by zhassan-aws** [comment]
I spent several hours yesterday trying to figure out a way to select a specific CBMC version in macOs. The only way I found is the one described in https://itnext.io/how-to-install-an-older-brew-package-add141e58d32. It only worked if I ran `brew install -s <raw-url>` though, which installs that specific version of CBMC from source. This took more than 50 minutes in my CI run: https://github.com/zhassan-aws/kani/runs/5545536856?check_suite_focus=true which is too high.

These are the changes for the reference: https://github.com/zhassan-aws/kani/commit/bc886c11c07be4639f81d8ff3d8be359bab9be3a

**Comment by zhassan-aws** [comment]
Dependent on https://github.com/diffblue/cbmc/issues/6739.

**Comment by tautschnig** [comment]
If you want/need fixed versions, see https://blog.sandipb.net/2021/09/02/installing-a-specific-version-of-a-homebrew-formula/ for how you can create a local tap. You should be able to do that as part of your CI workflow.

**Comment by tautschnig** [comment]
The above blog implements the official guidance (second last paragraph from https://docs.brew.sh/Versions).
